import { atlas } from "./atlas";
import { LINKAGE_KEYS } from "./installationReadinessReview";
import { EXECUTION_PERMISSION_CONFIRMATION, type ExecutionPermissionGrantCollectionV1, type ExecutionPermissionGrantCreateV1, type ExecutionPermissionGrantResultV1 } from "../types/executionPermissionGrant";

const UUID4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const UUID5 = /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const UTC = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/;
const HEX = /^[0-9a-f]{64}$/; const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const FP = ["algorithm", "canonicalization", "value"] as const;
const AUTHORITY = ["evidence_only", "execution_admission_granted", "execution_authorized", "installation_allowed", "dispatch_allowed", "agent_invocation_allowed", "worker_allowed", "workflow_allowed", "provider_mutation_allowed", "repository_mutation_allowed", "in_guest_mutation_allowed", "deployment_allowed", "rollback_allowed", "retry_allowed", "resend_allowed", "docker_allowed", "podman_allowed", "shell_allowed", "process_allowed", "replay_allowed"] as const;
const GRANT = ["schema", "grant_id", "operator_id", "candidate_record_id", "recorded_at", "valid_until", "record_state", "permission_scope", "confirmation_text", "confirmation_fingerprint", "linkage", "idempotency_key_fingerprint", "request_fingerprint", "statement", "permission_evidence_recorded", "grant_fingerprint", ...AUTHORITY] as const;
const STATUS = ["schema", "grant_id", "grant_fingerprint", "observed_at", "lifecycle", "permission_evidence_recorded", "evidence_only", "execution_admission_granted", "execution_authorized", "installation_allowed", "mutation_allowed", "replay_allowed", "status_fingerprint"] as const;
const AUDIT = ["schema", "grant_id", "candidate_record_id", "operator_fingerprint", "request_fingerprint", "idempotency_key_fingerprint", "confirmation_fingerprint", "v034_review_fingerprint", "linkage_fingerprint", "grant_fingerprint", "correlation_id", "occurred_at", "outcome", "evidence_only", "execution_attempted", "dispatch_attempted", "agent_invoked", "worker_started", "workflow_started", "process_started", "mutation_attempted", "retry_attempted", "replay_attempted", "evidence_fingerprint"] as const;
const ERROR = ["schema", "error_code", "safe_message", "correlation_id", "redacted", "retryable", "execution_admission_granted", "execution_authorized", "installation_allowed", "mutation_allowed", "replay_allowed"] as const;
const RESULT = ["disposition", "grant", "status", "audit_evidence", "error", ...AUTHORITY] as const;
const COLLECTION = ["grants", "evidence_only", "execution_authorized", "installation_allowed", "mutation_allowed", "replay_allowed"] as const;
const LINK = ["readiness_linkage", "v034_review_id", "v034_review_fingerprint", "v034_audit_evidence_fingerprint", "v034_operator_fingerprint", "linkage_fingerprint"] as const;
const ERRORS = ["malformed", "unauthenticated", "unauthorized", "not_found", "confirmation_mismatch", "not_readiness_gated", "expired", "conflict", "quota_exceeded", "unavailable"];

function obj(v: unknown): v is Record<string, unknown> { return typeof v === "object" && v !== null && !Array.isArray(v); }
function exact(v: Record<string, unknown>, keys: readonly string[]) { return Object.keys(v).length === keys.length && keys.every((k) => k in v); }
function utc(v: unknown): v is string { if (typeof v !== "string" || !UTC.test(v)) return false; const d = new Date(v); return !Number.isNaN(d.getTime()) && d.toISOString() === v.replace("Z", ".000Z"); }
function fp(v: unknown) { return obj(v) && exact(v, FP) && v.algorithm === "sha256" && v.canonicalization === "atlas-jcs-nfc-v1" && typeof v.value === "string" && HEX.test(v.value); }
function authorities(v: Record<string, unknown>) { return AUTHORITY.every((k) => v[k] === (k === "evidence_only")); }
function readinessLink(v: unknown) { if (!obj(v) || !exact(v, LINKAGE_KEYS)) return false; return LINKAGE_KEYS.every((k) => k === "v032_agent_receipt_atomicity_relied_upon" ? v[k] === true : k === "v032_agent_receipt_exported" ? v[k] === false : k.endsWith("_id") ? typeof v[k] === "string" && UUID4.test(v[k]) : fp(v[k])); }
function link(v: unknown) { return obj(v) && exact(v, LINK) && readinessLink(v.readiness_linkage) && typeof v.v034_review_id === "string" && UUID5.test(v.v034_review_id) && [v.v034_review_fingerprint, v.v034_audit_evidence_fingerprint, v.v034_operator_fingerprint, v.linkage_fingerprint].every(fp); }
function grant(v: unknown) { return obj(v) && exact(v, GRANT) && v.schema === "execution-permission-grant-v1" && typeof v.grant_id === "string" && UUID4.test(v.grant_id) && typeof v.operator_id === "string" && ID.test(v.operator_id) && typeof v.candidate_record_id === "string" && UUID4.test(v.candidate_record_id) && utc(v.recorded_at) && utc(v.valid_until) && v.record_state === "recorded" && v.permission_scope === "future_execution_admission_consideration_only" && v.confirmation_text === EXECUTION_PERMISSION_CONFIRMATION && [v.confirmation_fingerprint, v.idempotency_key_fingerprint, v.request_fingerprint, v.grant_fingerprint].every(fp) && link(v.linkage) && v.statement === "operator_recorded_exact_non_executing_permission_evidence" && v.permission_evidence_recorded === true && authorities(v); }
function status(v: unknown) { return obj(v) && exact(v, STATUS) && v.schema === "execution-permission-grant-status-v1" && typeof v.grant_id === "string" && UUID4.test(v.grant_id) && fp(v.grant_fingerprint) && utc(v.observed_at) && (v.lifecycle === "active" || v.lifecycle === "expired") && v.permission_evidence_recorded === true && v.evidence_only === true && ["execution_admission_granted", "execution_authorized", "installation_allowed", "mutation_allowed", "replay_allowed"].every((k) => v[k] === false) && fp(v.status_fingerprint); }
function nullableFp(v: unknown) { return v === null || fp(v); }
function audit(v: unknown) { return obj(v) && exact(v, AUDIT) && v.schema === "execution-permission-grant-audit-evidence-v1" && (v.grant_id === null || typeof v.grant_id === "string" && UUID4.test(v.grant_id)) && (v.candidate_record_id === null || typeof v.candidate_record_id === "string" && UUID4.test(v.candidate_record_id)) && fp(v.operator_fingerprint) && [v.request_fingerprint, v.idempotency_key_fingerprint, v.confirmation_fingerprint, v.v034_review_fingerprint, v.linkage_fingerprint, v.grant_fingerprint].every(nullableFp) && typeof v.correlation_id === "string" && ID.test(v.correlation_id) && utc(v.occurred_at) && ["recorded", "exact_duplicate", "rejected", "unavailable"].includes(String(v.outcome)) && v.evidence_only === true && ["execution_attempted", "dispatch_attempted", "agent_invoked", "worker_started", "workflow_started", "process_started", "mutation_attempted", "retry_attempted", "replay_attempted"].every((k) => v[k] === false) && fp(v.evidence_fingerprint); }
function error(v: unknown) { return obj(v) && exact(v, ERROR) && v.schema === "execution-permission-grant-error-v1" && ERRORS.includes(String(v.error_code)) && v.safe_message === "Execution permission evidence could not be recorded." && typeof v.correlation_id === "string" && ID.test(v.correlation_id) && v.redacted === true && v.retryable === false && ["execution_admission_granted", "execution_authorized", "installation_allowed", "mutation_allowed", "replay_allowed"].every((k) => v[k] === false); }
export function parseExecutionPermissionGrantResult(value: unknown): ExecutionPermissionGrantResultV1 { if (!obj(value) || !exact(value, RESULT) || !authorities(value)) throw new Error("Invalid execution permission grant response."); const ok = value.disposition === "recorded" || value.disposition === "exact_duplicate"; if (ok ? !grant(value.grant) || !status(value.status) || !audit(value.audit_evidence) || value.error !== null : !["rejected", "unavailable"].includes(String(value.disposition)) || value.grant !== null || value.status !== null || !error(value.error)) throw new Error("Invalid execution permission grant response."); if (ok) { const g = value.grant as Record<string, unknown>; const s = value.status as Record<string, unknown>; const a = value.audit_evidence as Record<string, unknown>; const recorded = new Date(String(g.recorded_at)).getTime(); const expires = new Date(String(g.valid_until)).getTime(); if (s.grant_id !== g.grant_id || a.grant_id !== g.grant_id || a.candidate_record_id !== g.candidate_record_id || a.outcome !== value.disposition || expires <= recorded || expires - recorded > 30_000) throw new Error("Invalid execution permission grant response."); } if (new TextEncoder().encode(JSON.stringify(value)).length > 128 * 1024) throw new Error("Invalid execution permission grant response."); return value as unknown as ExecutionPermissionGrantResultV1; }
export function parseExecutionPermissionGrantCollection(value: unknown): ExecutionPermissionGrantCollectionV1 { if (!obj(value) || !exact(value, COLLECTION) || !Array.isArray(value.grants) || value.evidence_only !== true || ["execution_authorized", "installation_allowed", "mutation_allowed", "replay_allowed"].some((k) => value[k] !== false)) throw new Error("Invalid execution permission grant collection."); return { ...value, grants: value.grants.map(parseExecutionPermissionGrantResult) } as ExecutionPermissionGrantCollectionV1; }

const path = (candidateId: string) => `/installation/candidate-records/${encodeURIComponent(candidateId)}/execution-permission-grants`;
export async function listExecutionPermissionGrants(candidateId: string) { const response = await atlas.get<unknown>(path(candidateId), { withCredentials: true }); return parseExecutionPermissionGrantCollection(response.data); }
export async function getExecutionPermissionGrant(candidateId: string, grantId: string) { const response = await atlas.get<unknown>(`${path(candidateId)}/${encodeURIComponent(grantId)}`, { withCredentials: true }); return parseExecutionPermissionGrantResult(response.data); }
export async function createExecutionPermissionGrant(candidateId: string, body: ExecutionPermissionGrantCreateV1, csrf: string, key: string) { const response = await atlas.post<unknown>(path(candidateId), body, { withCredentials: true, headers: { "X-Atlas-CSRF-Token": csrf, "Idempotency-Key": key } }); return parseExecutionPermissionGrantResult(response.data); }
export function executionPermissionGrantIdempotencyKey() { return `mission-control-permission-evidence-${crypto.randomUUID()}`; }
