import { atlas } from "./atlas";
import { LINKAGE_KEYS } from "./installationReadinessReview";
import type { InstallationExecutionAdmissionCollectionV1, InstallationExecutionAdmissionCreateV1, InstallationExecutionAdmissionResultV1 } from "../types/installationExecutionAdmission";

const UUID4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const UUID5 = /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const UTC = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/;
const HEX = /^[0-9a-f]{64}$/; const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const FP = ["algorithm", "canonicalization", "value"] as const;
const BLOCKERS = ["missing_evidence", "ownership_mismatch", "linkage_mismatch", "fingerprint_mismatch", "invalid_evidence", "stale_evidence", "expired_evidence", "grant_not_active", "grant_scope_mismatch", "grant_unavailable", "permission_denied", "subject_reserved", "installation_capability_unsupported", "runner_binding_not_defined", "execution_start_boundary_not_defined"] as const;
const AUTHORITY = ["evidence_only", "execution_start_allowed", "runner_binding_allowed", "execution_authorized", "installation_allowed", "dispatch_allowed", "retry_allowed", "resend_allowed", "agent_invocation_allowed", "worker_allowed", "workflow_allowed", "docker_allowed", "podman_allowed", "shell_allowed", "process_allowed", "provider_mutation_allowed", "repository_mutation_allowed", "in_guest_mutation_allowed", "deployment_allowed", "rollback_allowed", "replay_allowed"] as const;
const RESULT_AUTHORITY = ["evidence_only", "execution_authorized", "installation_allowed", "dispatch_allowed", "agent_invocation_allowed", "worker_allowed", "workflow_allowed", "mutation_allowed", "deployment_allowed", "rollback_allowed", "retry_allowed", "replay_allowed"] as const;
const ADMISSION = ["schema", "admission_id", "operator_id", "candidate_record_id", "recorded_at", "valid_until", "record_state", "readiness", "blockers", "scope", "linkage", "runner_eligibility", "idempotency_key_fingerprint", "request_fingerprint", "admission_evidence_recorded", "admission_fingerprint", ...AUTHORITY] as const;
const STATUS = ["schema", "admission_id", "admission_fingerprint", "observed_at", "lifecycle", "readiness", "evidence_only", "execution_authorized", "installation_allowed", "worker_allowed", "replay_allowed", "status_fingerprint"] as const;
const ELIGIBILITY = ["schema", "evaluation", "scope", "evaluated_at", "admission_gated", "runner_selected", "runner_registered", "runner_available", "runner_invocation_allowed", "worker_start_allowed", "workflow_start_allowed", "execution_start_boundary_defined", "evidence_only", "eligibility_fingerprint"] as const;
const GRANT_LINK = ["readiness_linkage", "v034_review_id", "v034_review_fingerprint", "v034_audit_evidence_fingerprint", "v034_operator_fingerprint", "linkage_fingerprint"] as const;
const LINK = ["permission_grant_linkage", "v035_grant_id", "v035_grant_fingerprint", "v035_status_fingerprint", "v035_request_fingerprint", "v035_confirmation_fingerprint", "v035_operator_fingerprint", "v034_review_fingerprint", "v034_audit_evidence_fingerprint", "chain_fingerprint", "linkage_fingerprint"] as const;
const AUDIT = ["schema", "admission_id", "candidate_record_id", "operator_fingerprint", "request_fingerprint", "idempotency_key_fingerprint", "v035_grant_fingerprint", "linkage_fingerprint", "eligibility_fingerprint", "admission_fingerprint", "blocker_codes", "correlation_id", "occurred_at", "outcome", "evidence_only", "execution_attempted", "dispatch_attempted", "agent_invoked", "worker_started", "workflow_started", "process_started", "mutation_attempted", "retry_attempted", "replay_attempted", "evidence_fingerprint"] as const;
const ERROR = ["schema", "error_code", "safe_message", "blocker_codes", "correlation_id", "redacted", "retryable", "evidence_only", "execution_authorized", "installation_allowed", "mutation_allowed", "replay_allowed"] as const;
const RESULT = ["disposition", "admission", "status", "audit_evidence", "error", ...RESULT_AUTHORITY] as const;
const COLLECTION = ["admissions", "evidence_only", "execution_start_allowed", "runner_binding_allowed", "execution_authorized", "installation_allowed", "dispatch_allowed", "mutation_allowed", "replay_allowed"] as const;

function obj(v: unknown): v is Record<string, unknown> { return typeof v === "object" && v !== null && !Array.isArray(v); }
function exact(v: Record<string, unknown>, keys: readonly string[]) { return Object.keys(v).length === keys.length && keys.every((key) => key in v); }
function utc(v: unknown): v is string { if (typeof v !== "string" || !UTC.test(v)) return false; const d = new Date(v); return !Number.isNaN(d.getTime()) && d.toISOString() === v.replace("Z", ".000Z"); }
function fp(v: unknown) { return obj(v) && exact(v, FP) && v.algorithm === "sha256" && v.canonicalization === "atlas-jcs-nfc-v1" && typeof v.value === "string" && HEX.test(v.value); }
function nullableFp(v: unknown) { return v === null || fp(v); }
function authority(v: Record<string, unknown>) { return AUTHORITY.every((key) => v[key] === (key === "evidence_only")); }
function resultAuthority(v: Record<string, unknown>) { return RESULT_AUTHORITY.every((key) => v[key] === (key === "evidence_only")); }
function blockerList(v: unknown) { return Array.isArray(v) && v.every((item, index) => typeof item === "string" && BLOCKERS.includes(item as typeof BLOCKERS[number]) && (index === 0 || BLOCKERS.indexOf(v[index - 1] as typeof BLOCKERS[number]) < BLOCKERS.indexOf(item as typeof BLOCKERS[number]))); }
function readinessLink(v: unknown) { if (!obj(v) || !exact(v, LINKAGE_KEYS)) return false; return LINKAGE_KEYS.every((key) => key === "v032_agent_receipt_atomicity_relied_upon" ? v[key] === true : key === "v032_agent_receipt_exported" ? v[key] === false : key.endsWith("_id") ? typeof v[key] === "string" && UUID4.test(v[key]) : fp(v[key])); }
function grantLink(v: unknown) { return obj(v) && exact(v, GRANT_LINK) && readinessLink(v.readiness_linkage) && typeof v.v034_review_id === "string" && UUID5.test(v.v034_review_id) && [v.v034_review_fingerprint, v.v034_audit_evidence_fingerprint, v.v034_operator_fingerprint, v.linkage_fingerprint].every(fp); }
function linkage(v: unknown) { return obj(v) && exact(v, LINK) && grantLink(v.permission_grant_linkage) && typeof v.v035_grant_id === "string" && UUID4.test(v.v035_grant_id) && [v.v035_grant_fingerprint, v.v035_status_fingerprint, v.v035_request_fingerprint, v.v035_confirmation_fingerprint, v.v035_operator_fingerprint, v.v034_review_fingerprint, v.v034_audit_evidence_fingerprint, v.chain_fingerprint, v.linkage_fingerprint].every(fp); }
function eligibility(v: unknown) { return obj(v) && exact(v, ELIGIBILITY) && v.schema === "installation-runner-eligibility-v1" && v.evaluation === "evidence_chain_eligible" && v.scope === "future_installation_runner_consideration_only" && utc(v.evaluated_at) && v.admission_gated === true && v.evidence_only === true && ["runner_selected", "runner_registered", "runner_available", "runner_invocation_allowed", "worker_start_allowed", "workflow_start_allowed", "execution_start_boundary_defined"].every((key) => v[key] === false) && fp(v.eligibility_fingerprint); }
function admission(v: unknown) { return obj(v) && exact(v, ADMISSION) && v.schema === "installation-execution-admission-v1" && typeof v.admission_id === "string" && UUID4.test(v.admission_id) && typeof v.operator_id === "string" && ID.test(v.operator_id) && typeof v.candidate_record_id === "string" && UUID4.test(v.candidate_record_id) && utc(v.recorded_at) && utc(v.valid_until) && v.record_state === "recorded" && v.readiness === "admission_gated" && Array.isArray(v.blockers) && v.blockers.length === 2 && v.blockers[0] === "runner_binding_not_defined" && v.blockers[1] === "execution_start_boundary_not_defined" && v.scope === "future_installation_runner_consideration_only" && linkage(v.linkage) && eligibility(v.runner_eligibility) && [v.idempotency_key_fingerprint, v.request_fingerprint, v.admission_fingerprint].every(fp) && v.admission_evidence_recorded === true && authority(v); }
function status(v: unknown) { return obj(v) && exact(v, STATUS) && v.schema === "installation-execution-admission-status-v1" && typeof v.admission_id === "string" && UUID4.test(v.admission_id) && fp(v.admission_fingerprint) && utc(v.observed_at) && (v.lifecycle === "active" || v.lifecycle === "expired") && v.readiness === "admission_gated" && v.evidence_only === true && ["execution_authorized", "installation_allowed", "worker_allowed", "replay_allowed"].every((key) => v[key] === false) && fp(v.status_fingerprint); }
function audit(v: unknown) { return obj(v) && exact(v, AUDIT) && v.schema === "installation-execution-admission-audit-evidence-v1" && (v.admission_id === null || typeof v.admission_id === "string" && UUID4.test(v.admission_id)) && (v.candidate_record_id === null || typeof v.candidate_record_id === "string" && UUID4.test(v.candidate_record_id)) && fp(v.operator_fingerprint) && [v.request_fingerprint, v.idempotency_key_fingerprint, v.v035_grant_fingerprint, v.linkage_fingerprint, v.eligibility_fingerprint, v.admission_fingerprint].every(nullableFp) && blockerList(v.blocker_codes) && typeof v.correlation_id === "string" && ID.test(v.correlation_id) && utc(v.occurred_at) && ["recorded", "exact_duplicate", "rejected", "unavailable"].includes(String(v.outcome)) && v.evidence_only === true && ["execution_attempted", "dispatch_attempted", "agent_invoked", "worker_started", "workflow_started", "process_started", "mutation_attempted", "retry_attempted", "replay_attempted"].every((key) => v[key] === false) && fp(v.evidence_fingerprint); }
function error(v: unknown) { return obj(v) && exact(v, ERROR) && v.schema === "installation-execution-admission-error-v1" && ["malformed", "unauthenticated", "unauthorized", "not_found", "not_eligible", "expired", "conflict", "quota_exceeded", "unavailable"].includes(String(v.error_code)) && v.safe_message === "Installation execution admission evidence could not be recorded." && blockerList(v.blocker_codes) && typeof v.correlation_id === "string" && ID.test(v.correlation_id) && v.redacted === true && v.retryable === false && v.evidence_only === true && ["execution_authorized", "installation_allowed", "mutation_allowed", "replay_allowed"].every((key) => v[key] === false); }

export function parseInstallationExecutionAdmissionResult(value: unknown): InstallationExecutionAdmissionResultV1 { if (!obj(value) || !exact(value, RESULT) || !resultAuthority(value)) throw new Error("Invalid installation execution admission response."); const ok = value.disposition === "recorded" || value.disposition === "exact_duplicate"; if (ok ? !admission(value.admission) || !status(value.status) || !audit(value.audit_evidence) || value.error !== null : !["rejected", "unavailable"].includes(String(value.disposition)) || value.admission !== null || value.status !== null || !error(value.error)) throw new Error("Invalid installation execution admission response."); if (ok) { const a = value.admission as Record<string, unknown>; const s = value.status as Record<string, unknown>; const e = value.audit_evidence as Record<string, unknown>; const recorded = new Date(String(a.recorded_at)).getTime(); const expires = new Date(String(a.valid_until)).getTime(); if (s.admission_id !== a.admission_id || e.admission_id !== a.admission_id || e.candidate_record_id !== a.candidate_record_id || e.outcome !== value.disposition || expires <= recorded || expires - recorded > 30_000) throw new Error("Invalid installation execution admission response."); } if (new TextEncoder().encode(JSON.stringify(value)).length > 128 * 1024) throw new Error("Invalid installation execution admission response."); return value as unknown as InstallationExecutionAdmissionResultV1; }
export function parseInstallationExecutionAdmissionCollection(value: unknown): InstallationExecutionAdmissionCollectionV1 { if (!obj(value) || !exact(value, COLLECTION) || !Array.isArray(value.admissions) || value.evidence_only !== true || COLLECTION.filter((key) => key !== "admissions" && key !== "evidence_only").some((key) => value[key] !== false)) throw new Error("Invalid installation execution admission collection."); return { ...value, admissions: value.admissions.map(parseInstallationExecutionAdmissionResult) } as InstallationExecutionAdmissionCollectionV1; }

const path = (candidateId: string) => `/installation/candidate-records/${encodeURIComponent(candidateId)}/execution-admissions`;
export async function listInstallationExecutionAdmissions(candidateId: string) { const response = await atlas.get<unknown>(path(candidateId), { withCredentials: true }); return parseInstallationExecutionAdmissionCollection(response.data); }
export async function getInstallationExecutionAdmission(candidateId: string, admissionId: string) { const response = await atlas.get<unknown>(`${path(candidateId)}/${encodeURIComponent(admissionId)}`, { withCredentials: true }); return parseInstallationExecutionAdmissionResult(response.data); }
export async function createInstallationExecutionAdmission(candidateId: string, body: InstallationExecutionAdmissionCreateV1, csrf: string, key: string) { const response = await atlas.post<unknown>(path(candidateId), body, { withCredentials: true, headers: { "X-Atlas-CSRF-Token": csrf, "Idempotency-Key": key } }); return parseInstallationExecutionAdmissionResult(response.data); }
export function installationExecutionAdmissionIdempotencyKey() { return `mission-control-admission-evidence-${crypto.randomUUID()}`; }
