import { atlas } from "./atlas";
import { isRunnerBindingLimits, isRunnerBindingPlanLinkage } from "./runnerBindingPlan";
import type { FingerprintV1 } from "../types/installationReadinessReview";
import type { WorkerAdmissionStubCollectionV1, WorkerAdmissionStubCreateV1, WorkerAdmissionStubResultV1 } from "../types/workerAdmissionStub";

const FP = ["algorithm", "canonicalization", "value"];
const CREATE = ["schema", "runner_binding_plan_id", "runner_binding_plan_fingerprint", "runner_binding_plan_valid_until", "worker_reference_id", "worker_reference_fingerprint", "inherited_limits_fingerprint", "requested_scope", "evidence_only", "worker_start_allowed", "queue_allowed", "dispatch_allowed", "execution_authorized", "replay_allowed"];
const INTENT_FALSE = ["queue_requested", "dispatch_requested", "worker_start_requested", "execution_requested", "agent_invocation_requested", "mutation_requested"];
const INTENT = ["schema", "intent_id", "operator_id", "candidate_record_id", "runner_binding_plan_id", "runner_binding_plan_fingerprint", "worker_reference_id", "worker_reference_fingerprint", "inherited_limits_fingerprint", "scope", "intent", "requested_at", "intent_fingerprint", ...INTENT_FALSE];
const INTAKE_FALSE = ["queue_selected", "queue_created", "intake_open", "payload_constructed", "request_serialized", "request_sent", "worker_contacted", "worker_started", "execution_authorized"];
const INTAKE = ["schema", "intent_id", "intent_fingerprint", "worker_reference_id", "worker_reference_fingerprint", "scope", "intake_state", "intake_protocol", "intake_fingerprint", ...INTAKE_FALSE];
const REFERENCE_FALSE = ["registered", "available", "reachable", "authenticated", "contacted", "reserved", "bound", "queue_known", "intake_open", "invocation_allowed"];
const REFERENCE = ["schema", "worker_reference_id", "owner_operator_id", "worker_kind", "trust_domain", "scope", "eligibility", "runner_reference_id", "runner_reference_fingerprint", "identity_fingerprint", "capability_profile_fingerprint", "inherited_limits", "inherited_limits_fingerprint", "valid_from", "valid_until", "reference_fingerprint", ...REFERENCE_FALSE];
const LINKAGE_FP = ["v020_v036_chain_fingerprint", "readiness_review_fingerprint", "permission_grant_fingerprint", "execution_admission_fingerprint", "runner_binding_plan_fingerprint", "runner_binding_plan_status_fingerprint", "runner_reference_fingerprint", "worker_reference_fingerprint", "worker_identity_fingerprint", "worker_capability_profile_fingerprint", "worker_admission_intent_fingerprint", "worker_admission_intake_fingerprint", "inherited_limits_fingerprint", "linkage_fingerprint"];
const LINKAGE = ["schema", "operator_id", "candidate_record_id", "runner_binding_plan_linkage", "v020_v036_chain_fingerprint", "readiness_review_fingerprint", "permission_grant_fingerprint", "execution_admission_id", "execution_admission_fingerprint", "runner_binding_plan_id", "runner_binding_plan_fingerprint", "runner_binding_plan_status_fingerprint", "runner_reference_id", "runner_reference_fingerprint", "worker_reference_id", "worker_reference_fingerprint", "worker_identity_fingerprint", "worker_capability_profile_fingerprint", "worker_admission_intent_fingerprint", "worker_admission_intake_fingerprint", "inherited_limits_fingerprint", "linkage_fingerprint"];
const AUTHORITY_FALSE = ["runner_binding_allowed", "worker_registered", "worker_contacted", "worker_reserved", "worker_bound", "worker_started", "queue_created", "queue_allowed", "work_enqueued", "enqueue_allowed", "dispatch_allowed", "execution_start_allowed", "execution_authorized", "installation_allowed", "retry_allowed", "resend_allowed", "agent_invocation_allowed", "workflow_allowed", "docker_allowed", "podman_allowed", "shell_allowed", "process_allowed", "provider_mutation_allowed", "repository_mutation_allowed", "in_guest_mutation_allowed", "deployment_allowed", "rollback_allowed", "replay_allowed"];
const STUB = ["schema", "stub_id", "operator_id", "candidate_record_id", "recorded_at", "valid_until", "record_state", "lifecycle", "eligibility", "blockers", "linkage", "worker_admission_intent", "worker_admission_intake", "worker_reference", "inherited_limits", "idempotency_key_fingerprint", "request_fingerprint", "stub_fingerprint", "evidence_only", ...AUTHORITY_FALSE];
const STATUS = ["schema", "stub_id", "observed_at", "lifecycle", "eligibility", "blockers", "status_fingerprint", "evidence_only", "worker_started", "work_enqueued", "execution_authorized", "replay_allowed"];
const AUDIT_FALSE = ["worker_contact_attempted", "worker_start_attempted", "enqueue_attempted", "dispatch_attempted", "execution_start_attempted", "agent_invocation_attempted", "workflow_start_attempted", "process_execution_attempted", "mutation_attempted", "replay_attempted", "effect_attempted"];
const AUDIT = ["schema", "event", "outcome", "operator_fingerprint", "candidate_record_fingerprint", "stub_fingerprint", "correlation_fingerprint", "occurred_at", "audit_fingerprint", "evidence_only", ...AUDIT_FALSE];
const ERROR_FALSE = ["worker_start_allowed", "enqueue_allowed", "dispatch_allowed", "execution_authorized", "mutation_allowed", "replay_allowed"];
const ERROR = ["schema", "error_code", "message", "correlation_fingerprint", "retryable", "redacted", "evidence_only", ...ERROR_FALSE];
const RESULT_FALSE = ["worker_registration_allowed", "worker_contact_allowed", "worker_reservation_allowed", "worker_binding_allowed", "worker_start_allowed", "queue_allowed", "enqueue_allowed", "dispatch_allowed", "execution_start_allowed", "execution_authorized", "installation_allowed", "agent_invocation_allowed", "workflow_allowed", "mutation_allowed", "deployment_allowed", "rollback_allowed", "retry_allowed", "replay_allowed"];
const RESULT = ["schema", "disposition", "stub", "status", "audit_evidence", "error", "evidence_only", ...RESULT_FALSE];
const COLLECTION = ["schema", "stubs", "evidence_only", "worker_start_allowed", "enqueue_allowed", "execution_authorized", "mutation_allowed"];
const HEX = /^[a-f0-9]{64}$/;
const UUID4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const UUID5 = /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const BLOCKERS = ["worker_not_started", "queue_boundary_not_defined", "execution_start_boundary_not_defined"];

function obj(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function exact(value: Record<string, unknown>, keys: string[]) { return Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key)); }
function fp(value: unknown): value is FingerprintV1 { return obj(value) && exact(value, FP) && value.algorithm === "sha256" && value.canonicalization === "atlas-jcs-nfc-v1" && typeof value.value === "string" && HEX.test(value.value); }
function instant(value: unknown) { return typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/.test(value) && Number.isFinite(Date.parse(value)); }
function falseFields(value: Record<string, unknown>, fields: string[]) { return fields.every((key) => value[key] === false); }
function blockers(value: unknown) { return Array.isArray(value) && value.length === 3 && BLOCKERS.every((item, index) => value[index] === item); }

function intent(value: unknown) { return obj(value) && exact(value, INTENT) && value.schema === "worker-admission-intent-v1" && typeof value.intent_id === "string" && UUID5.test(value.intent_id) && typeof value.operator_id === "string" && typeof value.candidate_record_id === "string" && UUID4.test(value.candidate_record_id) && typeof value.runner_binding_plan_id === "string" && UUID4.test(value.runner_binding_plan_id) && typeof value.worker_reference_id === "string" && UUID4.test(value.worker_reference_id) && value.scope === "installation_worker_admission_stub_only" && value.intent === "preserve_non_executing_worker_admission_evidence_only" && instant(value.requested_at) && ["runner_binding_plan_fingerprint", "worker_reference_fingerprint", "inherited_limits_fingerprint", "intent_fingerprint"].every((key) => fp(value[key])) && falseFields(value, INTENT_FALSE); }
function intake(value: unknown) { return obj(value) && exact(value, INTAKE) && value.schema === "worker-admission-intake-stub-v1" && typeof value.intent_id === "string" && UUID5.test(value.intent_id) && typeof value.worker_reference_id === "string" && UUID4.test(value.worker_reference_id) && fp(value.intent_fingerprint) && fp(value.worker_reference_fingerprint) && fp(value.intake_fingerprint) && value.scope === "installation_worker_admission_stub_only" && value.intake_state === "undefined" && value.intake_protocol === "none" && falseFields(value, INTAKE_FALSE); }
function reference(value: unknown) { return obj(value) && exact(value, REFERENCE) && value.schema === "installation-worker-reference-v1" && typeof value.worker_reference_id === "string" && UUID4.test(value.worker_reference_id) && typeof value.owner_operator_id === "string" && value.worker_kind === "isolated_installation_worker" && value.trust_domain === "atlas-installation" && value.scope === "installation_worker_admission_stub_only" && value.eligibility === "eligible_for_admission_stub_only" && typeof value.runner_reference_id === "string" && UUID4.test(value.runner_reference_id) && ["runner_reference_fingerprint", "identity_fingerprint", "capability_profile_fingerprint", "inherited_limits_fingerprint", "reference_fingerprint"].every((key) => fp(value[key])) && isRunnerBindingLimits(value.inherited_limits) && instant(value.valid_from) && instant(value.valid_until) && falseFields(value, REFERENCE_FALSE); }
function linkage(value: unknown) { return obj(value) && exact(value, LINKAGE) && value.schema === "worker-admission-stub-linkage-v1" && typeof value.operator_id === "string" && ["candidate_record_id", "execution_admission_id", "runner_binding_plan_id", "runner_reference_id", "worker_reference_id"].every((key) => typeof value[key] === "string" && UUID4.test(String(value[key]))) && isRunnerBindingPlanLinkage(value.runner_binding_plan_linkage) && LINKAGE_FP.every((key) => fp(value[key])); }
function stub(value: unknown) { if (!obj(value) || !exact(value, STUB) || value.schema !== "worker-admission-stub-v1" || typeof value.stub_id !== "string" || !UUID4.test(value.stub_id) || typeof value.operator_id !== "string" || typeof value.candidate_record_id !== "string" || !UUID4.test(value.candidate_record_id) || !instant(value.recorded_at) || !instant(value.valid_until) || value.record_state !== "recorded" || value.lifecycle !== "active" || value.eligibility !== "worker_admission_stubbed" || !blockers(value.blockers) || !linkage(value.linkage) || !intent(value.worker_admission_intent) || !intake(value.worker_admission_intake) || !reference(value.worker_reference) || !isRunnerBindingLimits(value.inherited_limits) || !["idempotency_key_fingerprint", "request_fingerprint", "stub_fingerprint"].every((key) => fp(value[key])) || value.evidence_only !== true || !falseFields(value, AUTHORITY_FALSE)) return false; const start = Date.parse(String(value.recorded_at)); const end = Date.parse(String(value.valid_until)); return end > start && end - start <= 30_000; }
function status(value: unknown) { return obj(value) && exact(value, STATUS) && value.schema === "worker-admission-stub-status-v1" && typeof value.stub_id === "string" && UUID4.test(value.stub_id) && instant(value.observed_at) && ["active", "expired"].includes(String(value.lifecycle)) && value.eligibility === "worker_admission_stubbed" && blockers(value.blockers) && fp(value.status_fingerprint) && value.evidence_only === true && falseFields(value, ["worker_started", "work_enqueued", "execution_authorized", "replay_allowed"]); }
function audit(value: unknown) { return obj(value) && exact(value, AUDIT) && value.schema === "worker-admission-stub-audit-evidence-v1" && ["worker_admission_stub_recorded", "worker_admission_stub_read"].includes(String(value.event)) && ["recorded", "exact_duplicate", "read", "blocked"].includes(String(value.outcome)) && fp(value.operator_fingerprint) && fp(value.candidate_record_fingerprint) && (value.stub_fingerprint === null || fp(value.stub_fingerprint)) && fp(value.correlation_fingerprint) && instant(value.occurred_at) && fp(value.audit_fingerprint) && value.evidence_only === true && falseFields(value, AUDIT_FALSE); }
function error(value: unknown) { return obj(value) && exact(value, ERROR) && value.schema === "worker-admission-stub-redacted-error-v1" && ["malformed", "unauthenticated", "unauthorized", "not_found", "not_eligible", "expired", "conflict", "quota_exceeded", "unavailable"].includes(String(value.error_code)) && value.message === "worker admission stub request could not be completed" && fp(value.correlation_fingerprint) && value.retryable === false && value.redacted === true && value.evidence_only === true && falseFields(value, ERROR_FALSE); }

export function parseWorkerAdmissionStubCreate(value: unknown): WorkerAdmissionStubCreateV1 { if (!obj(value) || !exact(value, CREATE) || value.schema !== "worker-admission-stub-create-v1" || typeof value.runner_binding_plan_id !== "string" || !UUID4.test(value.runner_binding_plan_id) || typeof value.worker_reference_id !== "string" || !UUID4.test(value.worker_reference_id) || !["runner_binding_plan_fingerprint", "worker_reference_fingerprint", "inherited_limits_fingerprint"].every((key) => fp(value[key])) || !instant(value.runner_binding_plan_valid_until) || value.requested_scope !== "installation_worker_admission_stub_only" || value.evidence_only !== true || !falseFields(value, ["worker_start_allowed", "queue_allowed", "dispatch_allowed", "execution_authorized", "replay_allowed"])) throw new Error("Invalid worker admission stub request."); return value as unknown as WorkerAdmissionStubCreateV1; }
export function parseWorkerAdmissionStubResult(value: unknown): WorkerAdmissionStubResultV1 { if (!obj(value) || !exact(value, RESULT) || value.schema !== "worker-admission-stub-result-v1" || value.evidence_only !== true || !falseFields(value, RESULT_FALSE)) throw new Error("Invalid worker admission stub response."); const success = ["recorded", "exact_duplicate", "read"].includes(String(value.disposition)); if (success ? !stub(value.stub) || !status(value.status) || !audit(value.audit_evidence) || value.error !== null : value.disposition !== "blocked" || value.stub !== null || value.status !== null || value.audit_evidence !== null || !error(value.error)) throw new Error("Invalid worker admission stub response."); if (success) { const record = value.stub as Record<string, unknown>; const state = value.status as Record<string, unknown>; const evidence = value.audit_evidence as Record<string, unknown>; if (state.stub_id !== record.stub_id || (evidence.stub_fingerprint as FingerprintV1).value !== (record.stub_fingerprint as FingerprintV1).value || evidence.outcome !== value.disposition) throw new Error("Invalid worker admission stub response."); } if (new TextEncoder().encode(JSON.stringify(value)).length > 128 * 1024) throw new Error("Invalid worker admission stub response."); return value as unknown as WorkerAdmissionStubResultV1; }
export function parseWorkerAdmissionStubCollection(value: unknown): WorkerAdmissionStubCollectionV1 { if (!obj(value) || !exact(value, COLLECTION) || value.schema !== "worker-admission-stub-collection-v1" || !Array.isArray(value.stubs) || value.stubs.length > 100 || value.evidence_only !== true || !falseFields(value, ["worker_start_allowed", "enqueue_allowed", "execution_authorized", "mutation_allowed"])) throw new Error("Invalid worker admission stub collection."); return { ...value, stubs: value.stubs.map(parseWorkerAdmissionStubResult) } as WorkerAdmissionStubCollectionV1; }

const path = (candidateId: string) => `/installation/candidate-records/${encodeURIComponent(candidateId)}/worker-admission-stubs`;
export async function listWorkerAdmissionStubs(candidateId: string) { const response = await atlas.get<unknown>(path(candidateId), { withCredentials: true }); return parseWorkerAdmissionStubCollection(response.data); }
export async function getWorkerAdmissionStub(candidateId: string, stubId: string) { const response = await atlas.get<unknown>(`${path(candidateId)}/${encodeURIComponent(stubId)}`, { withCredentials: true }); return parseWorkerAdmissionStubResult(response.data); }
export async function createWorkerAdmissionStub(candidateId: string, body: WorkerAdmissionStubCreateV1, csrf: string, key: string) { const response = await atlas.post<unknown>(path(candidateId), parseWorkerAdmissionStubCreate(body), { withCredentials: true, headers: { "X-Atlas-CSRF-Token": csrf, "Idempotency-Key": key } }); return parseWorkerAdmissionStubResult(response.data); }
export function workerAdmissionStubIdempotencyKey() { return `mission-control-worker-admission-stub-evidence-${crypto.randomUUID()}`; }
