import { atlas } from "./atlas";
import type { WorkerQueueReservationCollectionV1, WorkerQueueReservationCreateV1, WorkerQueueReservationResultV1 } from "../types/workerQueueReservation";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const fp = (value: unknown) => typeof value === "object" && value !== null && (value as Record<string, unknown>).algorithm === "sha256" && /^[0-9a-f]{64}$/.test(String((value as Record<string, unknown>).value));
const object = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const forbiddenTrue = (value: unknown) => object(value) && Object.entries(value).some(([key, item]) => (/(allowed|authorized|attempted|exists|reachable|contacted|started|enqueued|dequeued|claimed|executable|serialized|defined|released|consumed|replaceable|supersedable|bypass)/.test(key) && item === true));

export function parseWorkerQueueReservationCreate(value: unknown): WorkerQueueReservationCreateV1 { if (!object(value) || value.schema !== "worker-queue-reservation-create-v1" || value.requested_scope !== "installation_worker_queue_reservation_only" || value.evidence_only !== true || !UUID.test(String(value.worker_admission_stub_id)) || !UUID.test(String(value.queue_intake_reference_id)) || !UUID.test(String(value.queue_item_reference_id)) || !["worker_admission_stub_fingerprint", "queue_intake_reference_fingerprint", "queue_item_reference_fingerprint", "inherited_limits_fingerprint"].every((key) => fp(value[key])) || forbiddenTrue(value)) throw new Error("Invalid worker queue reservation request."); return value as WorkerQueueReservationCreateV1; }
export function parseWorkerQueueReservationResult(value: unknown): WorkerQueueReservationResultV1 { if (!object(value) || value.schema !== "worker-queue-reservation-result-v1" || value.evidence_only !== true || forbiddenTrue(value)) throw new Error("Invalid worker queue reservation response."); const success = ["recorded", "exact_duplicate", "read"].includes(String(value.disposition)); if (success) { const record = value.reservation; const status = value.status; const audit = value.audit_evidence; if (!object(record) || record.schema !== "worker-queue-reservation-v1" || record.eligibility !== "worker_queue_reservation_recorded" || !object(status) || status.schema !== "worker-queue-reservation-status-v1" || !object(audit) || audit.schema !== "worker-queue-reservation-audit-v1" || value.error !== null || forbiddenTrue(record) || forbiddenTrue(status) || forbiddenTrue(audit)) throw new Error("Invalid worker queue reservation response."); } else if (value.disposition !== "blocked" || value.reservation !== null || value.status !== null || value.audit_evidence !== null || !object(value.error) || value.error.redacted !== true || forbiddenTrue(value.error)) throw new Error("Invalid worker queue reservation response."); return value as WorkerQueueReservationResultV1; }
export function parseWorkerQueueReservationCollection(value: unknown): WorkerQueueReservationCollectionV1 { if (!object(value) || value.schema !== "worker-queue-reservation-collection-v1" || value.evidence_only !== true || !Array.isArray(value.items) || value.count !== value.items.length || value.items.length > 100 || forbiddenTrue(value)) throw new Error("Invalid worker queue reservation collection."); return { ...value, items: value.items.map(parseWorkerQueueReservationResult) } as WorkerQueueReservationCollectionV1; }
const path = (candidateId: string) => `/installation/candidate-records/${encodeURIComponent(candidateId)}/worker-queue-reservations`;
export async function listWorkerQueueReservations(candidateId: string) { const response = await atlas.get<unknown>(path(candidateId), { withCredentials: true }); return parseWorkerQueueReservationCollection(response.data); }
export async function getWorkerQueueReservation(candidateId: string, reservationId: string) { const response = await atlas.get<unknown>(`${path(candidateId)}/${encodeURIComponent(reservationId)}`, { withCredentials: true }); return parseWorkerQueueReservationResult(response.data); }
export async function createWorkerQueueReservation(candidateId: string, body: WorkerQueueReservationCreateV1, csrf: string, key: string) { const response = await atlas.post<unknown>(path(candidateId), parseWorkerQueueReservationCreate(body), { withCredentials: true, headers: { "X-Atlas-CSRF-Token": csrf, "Idempotency-Key": key } }); return parseWorkerQueueReservationResult(response.data); }
