import { atlas } from "./atlas";
import type { Fingerprint, RuntimeDefinitionRecord, RuntimeDefinitionResult, RuntimeDefinitionStatus } from "../types/workerActivationRuntimeDefinition";
const MAX_BYTES = 192 * 1024, UUID4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/, UUID5 = /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/, SHA = /^[a-f0-9]{64}$/;
const FAIL = "Runtime definition evidence is unavailable.";
const object = (v: unknown): Record<string, unknown> => { if (!v || typeof v !== "object" || Array.isArray(v)) throw new Error(FAIL); return v as Record<string, unknown>; };
const exact = (v: Record<string, unknown>, keys: string[]) => { if (Object.keys(v).length !== keys.length || Object.keys(v).some((key) => !keys.includes(key))) throw new Error(FAIL); };
const id = (v: unknown, re: RegExp) => { if (typeof v !== "string" || !re.test(v)) throw new Error(FAIL); return v; };
const utc = (v: unknown): v is string => typeof v === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/.test(v) && Number.isFinite(Date.parse(v));
const fp = (v: unknown): Fingerprint => { const r = object(v); exact(r, ["algorithm", "canonicalization", "value"]); if (r.algorithm !== "sha256" || r.canonicalization !== "atlas-jcs-nfc-v1" || typeof r.value !== "string" || !SHA.test(r.value)) throw new Error(FAIL); return r as Fingerprint; };
const bounded = (v: unknown) => { if (new TextEncoder().encode(JSON.stringify(v)).length > MAX_BYTES) throw new Error(FAIL); };
const AUTHORITY = ["evidence_only", "reference_only", "runtime_effect_allowed", "worker_start_allowed", "activation_allowed"];
function definition(value: unknown, candidateId: string, operatorId: string): RuntimeDefinitionRecord["definition"] { const r = object(value); exact(r, ["schema", "definition_id", "operator_id", "candidate_record_id", "runtime_name", "runtime_version", "artifact_digest", "capabilities", "lifecycle", "resources", "filesystem", "network", "valid_until", ...AUTHORITY, "definition_fingerprint"]); if (r.schema !== "worker-activation-runtime-definition-v1" || id(r.definition_id, UUID5) !== r.definition_id || r.operator_id !== operatorId || r.candidate_record_id !== candidateId || typeof r.runtime_name !== "string" || typeof r.runtime_version !== "string" || typeof r.artifact_digest !== "string" || !SHA.test(r.artifact_digest as string) || !Array.isArray(r.capabilities) || !r.capabilities.length || r.lifecycle !== "reference-only" || !utc(r.valid_until) || !AUTHORITY.every((key) => r[key] === (key === "evidence_only" || key === "reference_only"))) throw new Error(FAIL); object(r.resources); object(r.filesystem); object(r.network); fp(r.definition_fingerprint); return r as RuntimeDefinitionRecord["definition"]; }
function record(value: unknown, candidateId: string, operatorId: string): RuntimeDefinitionRecord { const r = object(value); exact(r, ["schema", "definition_id", "operator_id", "candidate_record_id", "recorded_at", "valid_until", "definition", "evaluation", "subject_fingerprint", "idempotency_key_fingerprint", "record_fingerprint"]); if (r.schema !== "worker-activation-runtime-definition-record-v1" || r.operator_id !== operatorId || r.candidate_record_id !== candidateId || !utc(r.recorded_at) || !utc(r.valid_until) || Date.parse(r.recorded_at as string) >= Date.parse(r.valid_until as string)) throw new Error(FAIL); const d = definition(r.definition, candidateId, operatorId); if (d.definition_id !== r.definition_id || d.valid_until !== r.valid_until) throw new Error(FAIL); const e = object(r.evaluation); exact(e, ["schema", "definition_id", "evaluated_at", "state", "eligibility", "refusal", "definition_fingerprint", "evaluation_fingerprint"]); if (e.schema !== "worker-activation-runtime-definition-evaluation-v1" || e.definition_id !== r.definition_id || !utc(e.evaluated_at) || (e.state === "recorded") !== (e.eligibility === "worker_activation_runtime_definition_recorded") || (e.state === "blocked") !== (e.refusal !== null) || JSON.stringify(e.definition_fingerprint) !== JSON.stringify(d.definition_fingerprint)) throw new Error(FAIL); for (const value of [r.subject_fingerprint, r.idempotency_key_fingerprint, r.record_fingerprint, e.evaluation_fingerprint]) fp(value); return r as RuntimeDefinitionRecord; }
function result(value: unknown, candidateId: string, operatorId: string, definitionId: string): RuntimeDefinitionResult { const r = object(value); exact(r, ["schema", "record", "status", "exact_duplicate"]); if (r.schema !== "worker-activation-runtime-definition-result-v1" || typeof r.exact_duplicate !== "boolean") throw new Error(FAIL); const item = record(r.record, candidateId, operatorId); if (item.definition_id !== definitionId) throw new Error(FAIL); const s = object(r.status); exact(s, ["schema", "definition_id", "operator_id", "candidate_record_id", "recorded_at", "valid_until", "lifecycle", "evaluation_fingerprint", "status_fingerprint"]); if (s.schema !== "worker-activation-runtime-definition-status-v1" || s.definition_id !== definitionId || s.operator_id !== operatorId || s.candidate_record_id !== candidateId || s.recorded_at !== item.recorded_at || s.valid_until !== item.valid_until || (s.lifecycle !== "active" && s.lifecycle !== "expired") || JSON.stringify(s.evaluation_fingerprint) !== JSON.stringify(object(item.evaluation).evaluation_fingerprint)) throw new Error(FAIL); fp(s.status_fingerprint); return { schema: r.schema as RuntimeDefinitionResult["schema"], record: item, status: s as RuntimeDefinitionStatus, exact_duplicate: r.exact_duplicate }; }
export async function listWorkerActivationRuntimeDefinitions(candidateId: string, operatorId: string): Promise<string[]> { id(candidateId, UUID4); const response = await atlas.get<unknown>(`/installation/candidate-records/${encodeURIComponent(candidateId)}/worker-activation-runtime-definitions`, { withCredentials: true }); bounded(response.data); const r = object(response.data); exact(r, ["schema", "operator_id", "candidate_record_id", "items", "count", "collection_fingerprint"]); if (r.schema !== "worker-activation-runtime-definition-collection-v1" || r.operator_id !== operatorId || r.candidate_record_id !== candidateId || !Array.isArray(r.items) || r.count !== r.items.length || r.items.length > 32) throw new Error(FAIL); fp(r.collection_fingerprint); const ids = r.items.map((item) => record(item, candidateId, operatorId).definition_id); if (new Set(ids).size !== ids.length) throw new Error(FAIL); return ids; }
export async function getWorkerActivationRuntimeDefinition(candidateId: string, operatorId: string, definitionId: string): Promise<RuntimeDefinitionResult> { id(candidateId, UUID4); id(definitionId, UUID5); const response = await atlas.get<unknown>(`/installation/candidate-records/${encodeURIComponent(candidateId)}/worker-activation-runtime-definitions/${encodeURIComponent(definitionId)}`, { withCredentials: true }); bounded(response.data); return result(response.data, candidateId, operatorId, definitionId); }
export function parseWorkerActivationRuntimeDefinitionResult(value: unknown, candidateId: string, operatorId: string, definitionId: string): RuntimeDefinitionResult { bounded(value); return result(value, candidateId, operatorId, definitionId); }
