import type { FingerprintV1 } from "./installationReadinessReview";
import type { RunnerBindingLimitsV1 } from "./runnerBindingPlan";
import type { WorkerQueueReservationLinkageV1 } from "./workerQueueReservation";

export type WorkerIntakeAdmissionCreateV1 = {
    schema: "worker-intake-admission-create-v1";
    worker_queue_reservation_id: string;
    worker_queue_reservation_fingerprint: FingerprintV1;
    worker_queue_reservation_valid_until: string;
    worker_identity_id: string;
    worker_identity_fingerprint: FingerprintV1;
    worker_intake_reference_id: string;
    worker_intake_reference_fingerprint: FingerprintV1;
    inherited_limits_fingerprint: FingerprintV1;
    requested_scope: "installation_worker_intake_admission_only";
    evidence_only: true;
    live_enqueue_allowed: false;
    dequeue_allowed: false;
    worker_start_allowed: false;
    execution_authorized: false;
    replay_allowed: false;
};

export type WorkerIntakeAuthorityV1 = {
    evidence_only: true;
    live_enqueue_allowed: false;
    dequeue_allowed: false;
    queue_polling_allowed: false;
    worker_contact_allowed: false;
    worker_start_allowed: false;
    execution_start_allowed: false;
    runner_binding_allowed: false;
    dispatch_allowed: false;
    retry_allowed: false;
    resend_allowed: false;
    agent_invocation_allowed: false;
    workflow_start_allowed: false;
    docker_execution_allowed: false;
    podman_execution_allowed: false;
    shell_execution_allowed: false;
    process_execution_allowed: false;
    provider_mutation_allowed: false;
    repository_mutation_allowed: false;
    in_guest_mutation_allowed: false;
    installation_allowed: false;
    deployment_allowed: false;
    rollback_allowed: false;
    replay_bypass_allowed: false;
};

export type WorkerIntakeWorkerIdentityV1 = {
    schema: "worker-intake-worker-identity-v1";
    worker_identity_id: string;
    owner_operator_id: string;
    candidate_record_id: string;
    worker_queue_reservation_id: string;
    worker_queue_reservation_fingerprint: FingerprintV1;
    worker_reference_id: string;
    worker_reference_fingerprint: FingerprintV1;
    queue_intake_reference_id: string;
    queue_intake_reference_fingerprint: FingerprintV1;
    queue_item_reference_id: string;
    queue_item_reference_fingerprint: FingerprintV1;
    worker_kind: "isolated_installation_worker";
    trust_domain: "atlas-installation";
    scope: "installation_worker_intake_admission_only";
    eligibility: "eligible_for_intake_admission_evidence_only";
    identity_fingerprint: FingerprintV1;
    capability_profile_fingerprint: FingerprintV1;
    inherited_limits: RunnerBindingLimitsV1;
    inherited_limits_fingerprint: FingerprintV1;
    valid_from: string;
    valid_until: string;
    registered: false;
    available: false;
    reachable: false;
    authenticated: false;
    contacted: false;
    reserved: false;
    started: false;
    execution_allowed: false;
    worker_identity_fingerprint: FingerprintV1;
};

export type WorkerIntakeReferenceV1 = {
    schema: "worker-intake-reference-v1";
    worker_intake_reference_id: string;
    owner_operator_id: string;
    candidate_record_id: string;
    worker_queue_reservation_id: string;
    worker_queue_reservation_fingerprint: FingerprintV1;
    worker_identity_id: string;
    worker_identity_fingerprint: FingerprintV1;
    queue_intake_reference_id: string;
    queue_intake_reference_fingerprint: FingerprintV1;
    queue_item_reference_id: string;
    queue_item_reference_fingerprint: FingerprintV1;
    intake_kind: "abstract_worker_intake";
    trust_domain: "atlas-installation";
    scope: "installation_worker_intake_admission_only";
    eligibility: "eligible_for_intake_admission_evidence_only";
    valid_from: string;
    valid_until: string;
    intake_reference_fingerprint: FingerprintV1;
    intake_protocol: "none";
    intake_exists: false;
    intake_open: false;
    endpoint_known: false;
    credential_known: false;
    payload_schema_defined: false;
    serialization_allowed: false;
    live_enqueue_allowed: false;
    worker_start_allowed: false;
};

export type WorkerIntakeAdmissionDecisionV1 = {
    schema: "worker-intake-admission-decision-v1";
    decision_id: string;
    owner_operator_id: string;
    candidate_record_id: string;
    worker_queue_reservation_id: string;
    worker_queue_reservation_fingerprint: FingerprintV1;
    worker_identity_id: string;
    worker_identity_fingerprint: FingerprintV1;
    worker_intake_reference_id: string;
    worker_intake_reference_fingerprint: FingerprintV1;
    scope: "installation_worker_intake_admission_only";
    decision: "preserve_non_executing_worker_intake_admission_evidence_only";
    evaluated_at: string;
    eligibility: "worker_intake_admission_recorded";
    blockers: string[];
    inherited_limits_fingerprint: FingerprintV1;
    decision_fingerprint: FingerprintV1;
    payload_constructed: false;
    request_serialized: false;
    request_sent: false;
    queue_enqueued: false;
    queue_dequeued: false;
    worker_contacted: false;
    worker_started: false;
    execution_authorized: false;
};

export type WorkerIntakeAdmissionLinkageV1 = {
    schema: "worker-intake-admission-linkage-v1";
    operator_id: string;
    candidate_record_id: string;
    worker_queue_reservation_linkage: WorkerQueueReservationLinkageV1;
    v020_v038_chain_fingerprint: FingerprintV1;
    readiness_review_fingerprint: FingerprintV1;
    permission_grant_fingerprint: FingerprintV1;
    execution_admission_id: string;
    execution_admission_fingerprint: FingerprintV1;
    runner_binding_plan_id: string;
    runner_binding_plan_fingerprint: FingerprintV1;
    runner_binding_plan_status_fingerprint: FingerprintV1;
    runner_reference_id: string;
    runner_reference_fingerprint: FingerprintV1;
    worker_admission_stub_id: string;
    worker_admission_stub_fingerprint: FingerprintV1;
    worker_admission_stub_status_fingerprint: FingerprintV1;
    worker_reference_id: string;
    worker_reference_fingerprint: FingerprintV1;
    queue_reservation_id: string;
    queue_reservation_fingerprint: FingerprintV1;
    queue_reservation_status_fingerprint: FingerprintV1;
    queue_intake_reference_id: string;
    queue_intake_reference_fingerprint: FingerprintV1;
    queue_item_reference_id: string;
    queue_item_reference_fingerprint: FingerprintV1;
    worker_identity_id: string;
    worker_identity_fingerprint: FingerprintV1;
    worker_intake_reference_id: string;
    worker_intake_reference_fingerprint: FingerprintV1;
    worker_intake_admission_decision_fingerprint: FingerprintV1;
    inherited_limits_fingerprint: FingerprintV1;
    linkage_fingerprint: FingerprintV1;
};

export type WorkerIntakeAdmissionV1 = WorkerIntakeAuthorityV1 & {
    schema: "worker-intake-admission-v1";
    admission_id: string;
    operator_id: string;
    candidate_record_id: string;
    recorded_at: string;
    valid_until: string;
    record_state: "recorded";
    lifecycle: "active";
    eligibility: "worker_intake_admission_recorded";
    blockers: string[];
    linkage: WorkerIntakeAdmissionLinkageV1;
    worker_identity: WorkerIntakeWorkerIdentityV1;
    worker_intake_reference: WorkerIntakeReferenceV1;
    admission_decision: WorkerIntakeAdmissionDecisionV1;
    inherited_limits: RunnerBindingLimitsV1;
    idempotency_key_fingerprint: FingerprintV1;
    request_fingerprint: FingerprintV1;
    subject_fingerprint: FingerprintV1;
    record_fingerprint: FingerprintV1;
};

export type WorkerIntakeAdmissionStatusV1 = WorkerIntakeAuthorityV1 & {
    schema: "worker-intake-admission-status-v1";
    admission_id: string;
    operator_id: string;
    candidate_record_id: string;
    evaluated_at: string;
    valid_until: string;
    lifecycle: "active" | "expired";
    eligibility: "worker_intake_admission_recorded" | "readiness_gated" | "blocked";
    blockers: string[];
    record_fingerprint: FingerprintV1;
    status_fingerprint: FingerprintV1;
};

export type WorkerIntakeAdmissionAuditV1 = WorkerIntakeAuthorityV1 & {
    schema: "worker-intake-admission-audit-v1";
    event: "intake_admission_recorded" | "intake_admission_read";
    outcome: "recorded" | "exact_duplicate" | "read" | "blocked";
    operator_fingerprint: FingerprintV1;
    candidate_record_fingerprint: FingerprintV1;
    admission_id: string | null;
    subject_fingerprint: FingerprintV1 | null;
    record_fingerprint: FingerprintV1 | null;
    correlation_fingerprint: FingerprintV1;
    occurred_at: string;
    audit_fingerprint: FingerprintV1;
};

export type WorkerIntakeAdmissionResultV1 = WorkerIntakeAuthorityV1 & {
    schema: "worker-intake-admission-result-v1";
    ok: boolean;
    admission: WorkerIntakeAdmissionV1 | null;
    error: Record<string, unknown> | null;
    correlation_fingerprint: FingerprintV1;
};

export type WorkerIntakeAdmissionCollectionV1 = WorkerIntakeAuthorityV1 & {
    schema: "worker-intake-admission-collection-v1";
    operator_id: string;
    candidate_record_id: string;
    items: WorkerIntakeAdmissionV1[];
    count: number;
    collection_fingerprint: FingerprintV1;
};
