import type { FingerprintV1 } from "./installationReadinessReview";
import type { RunnerBindingLimitsV1 } from "./runnerBindingPlan";
import type { WorkerAdmissionStubLinkageV1 } from "./workerAdmissionStub";

export type WorkerQueueReservationCreateV1 = {
    schema: "worker-queue-reservation-create-v1"; worker_admission_stub_id: string;
    worker_admission_stub_fingerprint: FingerprintV1; worker_admission_stub_valid_until: string;
    queue_intake_reference_id: string; queue_intake_reference_fingerprint: FingerprintV1;
    queue_item_reference_id: string; queue_item_reference_fingerprint: FingerprintV1;
    inherited_limits_fingerprint: FingerprintV1; requested_scope: "installation_worker_queue_reservation_only";
    evidence_only: true; live_enqueue_allowed: false; dequeue_allowed: false;
    worker_start_allowed: false; execution_authorized: false; replay_allowed: false;
};
export type QueueIntakeReferenceV1 = { schema: "worker-queue-intake-reference-v1"; queue_intake_reference_id: string; owner_operator_id: string; candidate_record_id: string; worker_admission_stub_id: string; worker_admission_stub_fingerprint: FingerprintV1; worker_reference_id: string; worker_reference_fingerprint: FingerprintV1; queue_kind: "abstract_installation_queue"; trust_domain: "atlas-installation"; scope: "installation_worker_queue_reservation_only"; eligibility: "eligible_for_reservation_evidence_only"; identity_fingerprint: FingerprintV1; capability_fingerprint: FingerprintV1; inherited_limits: RunnerBindingLimitsV1; inherited_limits_fingerprint: FingerprintV1; valid_from: string; valid_until: string; reference_fingerprint: FingerprintV1; queue_exists: false; queue_reachable: false; queue_authenticated: false; queue_contacted: false; reservation_endpoint_known: false; live_enqueue_allowed: false; dequeue_allowed: false };
export type QueueItemReferenceV1 = { schema: "worker-queue-item-reference-v1"; queue_item_reference_id: string; owner_operator_id: string; candidate_record_id: string; worker_admission_stub_id: string; worker_admission_stub_fingerprint: FingerprintV1; queue_intake_reference_id: string; queue_intake_reference_fingerprint: FingerprintV1; worker_reference_id: string; worker_reference_fingerprint: FingerprintV1; item_kind: "installation_evidence_reference_only"; scope: "installation_worker_queue_reservation_only"; inherited_limits_fingerprint: FingerprintV1; created_at: string; item_fingerprint: FingerprintV1; payload_defined: false; serialized: false; enqueued: false; dequeued: false; claimed: false; executable: false };
export type WorkerQueueReservationLinkageV1 = { schema: "worker-queue-reservation-linkage-v1"; operator_id: string; candidate_record_id: string; worker_admission_stub_linkage: WorkerAdmissionStubLinkageV1; v020_v037_chain_fingerprint: FingerprintV1; readiness_review_fingerprint: FingerprintV1; permission_grant_fingerprint: FingerprintV1; execution_admission_id: string; execution_admission_fingerprint: FingerprintV1; runner_binding_plan_id: string; runner_binding_plan_fingerprint: FingerprintV1; runner_binding_plan_status_fingerprint: FingerprintV1; runner_reference_id: string; runner_reference_fingerprint: FingerprintV1; worker_admission_stub_id: string; worker_admission_stub_fingerprint: FingerprintV1; worker_admission_stub_status_fingerprint: FingerprintV1; worker_reference_id: string; worker_reference_fingerprint: FingerprintV1; worker_admission_intent_fingerprint: FingerprintV1; worker_intake_stub_fingerprint: FingerprintV1; queue_intake_reference_id: string; queue_intake_reference_fingerprint: FingerprintV1; queue_item_reference_id: string; queue_item_reference_fingerprint: FingerprintV1; inherited_limits_fingerprint: FingerprintV1; linkage_fingerprint: FingerprintV1 };
export type WorkerQueueReservationV1 = { schema: "worker-queue-reservation-v1"; reservation_id: string; operator_id: string; candidate_record_id: string; recorded_at: string; valid_until: string; record_state: "recorded"; lifecycle: "active"; eligibility: "worker_queue_reservation_recorded"; blockers: string[]; linkage: WorkerQueueReservationLinkageV1; queue_intake_reference: QueueIntakeReferenceV1; queue_item_reference: QueueItemReferenceV1; inherited_limits: RunnerBindingLimitsV1; idempotency_key_fingerprint: FingerprintV1; request_fingerprint: FingerprintV1; subject_fingerprint: FingerprintV1; record_fingerprint: FingerprintV1; evidence_only: true; [key: string]: unknown };
export type WorkerQueueReservationStatusV1 = { schema: "worker-queue-reservation-status-v1"; reservation_id: string; operator_id: string; candidate_record_id: string; observed_at: string; valid_until: string; lifecycle: "active" | "expired"; eligibility: "worker_queue_reservation_recorded" | "readiness_gated" | "blocked"; blockers: string[]; record_fingerprint: FingerprintV1; status_fingerprint: FingerprintV1; [key: string]: unknown };
export type WorkerQueueReservationAuditV1 = { schema: "worker-queue-reservation-audit-v1"; event: "reservation_recorded" | "reservation_read"; outcome: "recorded" | "exact_duplicate" | "read" | "blocked"; operator_fingerprint: FingerprintV1; candidate_record_fingerprint: FingerprintV1; reservation_id: string | null; subject_fingerprint: FingerprintV1 | null; record_fingerprint: FingerprintV1 | null; correlation_fingerprint: FingerprintV1; occurred_at: string; audit_fingerprint: FingerprintV1; evidence_only: true; [key: string]: unknown };
export type WorkerQueueReservationResultV1 = { schema: "worker-queue-reservation-result-v1"; disposition: "recorded" | "exact_duplicate" | "read" | "blocked"; reservation: WorkerQueueReservationV1 | null; status: WorkerQueueReservationStatusV1 | null; audit_evidence: WorkerQueueReservationAuditV1 | null; error: Record<string, unknown> | null; evidence_only: true; [key: string]: unknown };
export type WorkerQueueReservationCollectionV1 = { schema: "worker-queue-reservation-collection-v1"; items: WorkerQueueReservationResultV1[]; count: number; evidence_only: true; [key: string]: unknown };
