import { fp } from "./installationReadinessReview";
import { queueObservationReceiptFixture, queueObservationResultFixture } from "./queueObservation";
import type { ControlledDequeueAdmissionAuthorityV1, ControlledDequeueAdmissionCollectionV1, ControlledDequeueAdmissionResultV1, ControlledDequeueAdmissionV1 } from "../types/controlledDequeueAdmission";

export const controlledDequeueAdmissionAuthority: ControlledDequeueAdmissionAuthorityV1 = {
    evidence_only: true,
    reference_only: true,
    payload_schema_defined: false,
    payload_constructed: false,
    payload_serialized: false,
    payload_bytes: 0,
    executable_payload_allowed: false,
    dequeue_defined: false,
    dequeue_allowed: false,
    dequeue_attempted: false,
    dequeued: false,
    queue_polling_allowed: false,
    queue_polled: false,
    queue_claim_allowed: false,
    queue_claimed: false,
    queue_lease_allowed: false,
    queue_leased: false,
    queue_ack_allowed: false,
    queue_acked: false,
    queue_consumed: false,
    worker_contact_allowed: false,
    worker_contacted: false,
    worker_start_allowed: false,
    worker_started: false,
    agent_invocation_allowed: false,
    execution_start_allowed: false,
    process_execution_allowed: false,
    dispatch_allowed: false,
    retry_allowed: false,
    resend_allowed: false,
    scheduler_allowed: false,
    workflow_start_allowed: false,
    docker_execution_allowed: false,
    podman_execution_allowed: false,
    container_execution_allowed: false,
    shell_execution_allowed: false,
    provider_mutation_allowed: false,
    repository_mutation_allowed: false,
    in_guest_mutation_allowed: false,
    installation_allowed: false,
    deployment_allowed: false,
    rollback_allowed: false,
    replay_bypass_allowed: false,
};

const blockers = ["dequeue_not_defined", "queue_polling_not_defined", "queue_claim_not_defined", "queue_lease_not_defined", "queue_ack_not_defined", "worker_start_not_defined", "execution_start_boundary_not_defined"] as const;
const admissionId = "4b3beb58-c4b9-5b2b-9995-4f629abefaf6";

export const controlledDequeueAdmissionFixture: ControlledDequeueAdmissionV1 = {
    ...controlledDequeueAdmissionAuthority,
    schema: "controlled-dequeue-admission-v1",
    admission_id: admissionId,
    operator_id: queueObservationReceiptFixture.operator_id,
    candidate_record_id: queueObservationReceiptFixture.candidate_record_id,
    recorded_at: "2099-08-27T12:00:48Z",
    valid_until: "2099-08-27T12:01:12Z",
    lifecycle: "active",
    admission_state: "readiness_gated",
    disposition: "controlled_dequeue_admission_recorded",
    eligibility: "eligible_for_later_dequeue_consideration",
    blockers: [...blockers],
    queue_observation_receipt: queueObservationReceiptFixture,
    queue_observation_receipt_status: queueObservationResultFixture.status!,
    inherited_limits: queueObservationReceiptFixture.v042_enqueue.inherited_limits,
    admission_decision: {
        ...controlledDequeueAdmissionAuthority,
        schema: "controlled-dequeue-admission-decision-v1",
        decision: "eligible_for_later_dequeue_consideration",
        admission_state: "readiness_gated",
        blockers: [...blockers],
        queue_identity_fingerprint: fp,
        item_identity_fingerprint: fp,
        lineage_fingerprint: fp,
        inherited_limits_fingerprint: queueObservationReceiptFixture.v042_enqueue.inherited_limits.limits_fingerprint,
        decision_fingerprint: fp,
    },
    queue_identity_fingerprint: fp,
    item_identity_fingerprint: fp,
    lineage_fingerprint: fp,
    subject_fingerprint: fp,
    admission_record_fingerprint: fp,
    controlled_dequeue_admission_recorded: true,
};

export const controlledDequeueAdmissionCollectionFixture: ControlledDequeueAdmissionCollectionV1 = {
    ...controlledDequeueAdmissionAuthority,
    schema: "controlled-dequeue-admission-collection-v1",
    operator_id: controlledDequeueAdmissionFixture.operator_id,
    candidate_record_id: controlledDequeueAdmissionFixture.candidate_record_id,
    items: [controlledDequeueAdmissionFixture],
    count: 1,
    collection_fingerprint: fp,
    controlled_dequeue_admission_recorded: false,
};

export const controlledDequeueAdmissionResultFixture: ControlledDequeueAdmissionResultV1 = {
    ...controlledDequeueAdmissionAuthority,
    schema: "controlled-dequeue-admission-result-v1",
    ok: true,
    outcome: "success",
    record: controlledDequeueAdmissionFixture,
    status: {
        ...controlledDequeueAdmissionAuthority,
        schema: "controlled-dequeue-admission-status-v1",
        admission_id: admissionId,
        operator_id: controlledDequeueAdmissionFixture.operator_id,
        candidate_record_id: controlledDequeueAdmissionFixture.candidate_record_id,
        lifecycle: "active",
        admission_state: "readiness_gated",
        eligibility: "eligible_for_later_dequeue_consideration",
        blockers: [...blockers],
        evaluated_at: "2099-08-27T12:00:49Z",
        valid_until: "2099-08-27T12:01:12Z",
        admission_record_fingerprint: fp,
        status_fingerprint: fp,
        controlled_dequeue_admission_recorded: true,
    },
    error: null,
    correlation_fingerprint: fp,
    controlled_dequeue_admission_recorded: true,
};

export const ambiguousControlledDequeueAdmissionResultFixture: ControlledDequeueAdmissionResultV1 = {
    ...controlledDequeueAdmissionAuthority,
    schema: "controlled-dequeue-admission-result-v1",
    ok: false,
    outcome: "failure",
    record: null,
    status: null,
    error: {
        ...controlledDequeueAdmissionAuthority,
        schema: "controlled-dequeue-admission-error-v1",
        error_code: "ambiguous_state",
        message: "controlled dequeue admission request could not be completed",
        retryable: false,
        correlation_fingerprint: fp,
        redacted: true,
        controlled_dequeue_admission_recorded: false,
    },
    correlation_fingerprint: fp,
    controlled_dequeue_admission_recorded: false,
};
