import type { FingerprintV1 } from "../types/installationReadinessReview";
import type { LiveEnqueueAdmissionCollectionV1, LiveEnqueueAdmissionResultV1, LiveEnqueueAdmissionV1 } from "../types/liveEnqueueAdmission";
import { workerIntakeAdmissionFixture } from "./workerIntakeAdmission";

const fp = (value: string): FingerprintV1 => ({ algorithm: "sha256", canonicalization: "atlas-jcs-nfc-v1", value: value.repeat(64) });
const intake = workerIntakeAdmissionFixture;
const authority = {
    evidence_only: true as const,
    live_enqueue_allowed: false as const,
    enqueue_operation_defined: false as const,
    queue_item_payload_defined: false as const,
    payload_constructed: false as const,
    payload_serialized: false as const,
    queue_publish_allowed: false as const,
    queue_send_allowed: false as const,
    dequeue_allowed: false as const,
    queue_polling_allowed: false as const,
    queue_claim_allowed: false as const,
    queue_ack_allowed: false as const,
    worker_contact_allowed: false as const,
    worker_authentication_allowed: false as const,
    worker_binding_allowed: false as const,
    worker_start_allowed: false as const,
    execution_start_allowed: false as const,
    runner_binding_allowed: false as const,
    dispatch_allowed: false as const,
    retry_allowed: false as const,
    resend_allowed: false as const,
    agent_invocation_allowed: false as const,
    workflow_start_allowed: false as const,
    docker_execution_allowed: false as const,
    podman_execution_allowed: false as const,
    shell_execution_allowed: false as const,
    process_execution_allowed: false as const,
    provider_mutation_allowed: false as const,
    repository_mutation_allowed: false as const,
    in_guest_mutation_allowed: false as const,
    installation_allowed: false as const,
    deployment_allowed: false as const,
    rollback_allowed: false as const,
    replay_bypass_allowed: false as const,
};
const blockers = ["enqueue_operation_not_defined", "dequeue_not_defined", "worker_start_not_defined", "execution_start_boundary_not_defined"] as const;
const decisionFingerprint = fp("e");
const recordFingerprint = fp("f");

export const liveEnqueueAdmissionFixture: LiveEnqueueAdmissionV1 = {
    schema: "live-enqueue-admission-v1",
    admission_id: "98a1c151-8a02-5c97-9d0d-2c85ea1fa570",
    operator_id: intake.operator_id,
    candidate_record_id: intake.candidate_record_id,
    recorded_at: "2099-08-27T12:00:42Z",
    valid_until: "2099-08-27T12:01:12Z",
    record_state: "recorded",
    lifecycle: "active",
    eligibility: "live_enqueue_admission_recorded",
    blockers: [...blockers],
    scope: "installation_live_enqueue_admission_only",
    linkage: {
        schema: "live-enqueue-admission-linkage-v1",
        operator_id: intake.operator_id,
        candidate_record_id: intake.candidate_record_id,
        worker_intake_admission_linkage: intake.linkage,
        v020_v039_chain_fingerprint: fp("1"),
        readiness_review_fingerprint: intake.linkage.readiness_review_fingerprint,
        permission_grant_fingerprint: intake.linkage.permission_grant_fingerprint,
        execution_admission_id: intake.linkage.execution_admission_id,
        execution_admission_fingerprint: intake.linkage.execution_admission_fingerprint,
        runner_binding_plan_id: intake.linkage.runner_binding_plan_id,
        runner_binding_plan_fingerprint: intake.linkage.runner_binding_plan_fingerprint,
        runner_binding_plan_status_fingerprint: intake.linkage.runner_binding_plan_status_fingerprint,
        runner_reference_id: intake.linkage.runner_reference_id,
        runner_reference_fingerprint: intake.linkage.runner_reference_fingerprint,
        worker_admission_stub_id: intake.linkage.worker_admission_stub_id,
        worker_admission_stub_fingerprint: intake.linkage.worker_admission_stub_fingerprint,
        worker_admission_stub_status_fingerprint: intake.linkage.worker_admission_stub_status_fingerprint,
        worker_reference_id: intake.linkage.worker_reference_id,
        worker_reference_fingerprint: intake.linkage.worker_reference_fingerprint,
        queue_reservation_id: intake.linkage.queue_reservation_id,
        queue_reservation_fingerprint: intake.linkage.queue_reservation_fingerprint,
        queue_reservation_status_fingerprint: intake.linkage.queue_reservation_status_fingerprint,
        queue_intake_reference_id: intake.linkage.queue_intake_reference_id,
        queue_intake_reference_fingerprint: intake.linkage.queue_intake_reference_fingerprint,
        queue_item_reference_id: intake.linkage.queue_item_reference_id,
        queue_item_reference_fingerprint: intake.linkage.queue_item_reference_fingerprint,
        worker_identity_id: intake.linkage.worker_identity_id,
        worker_identity_fingerprint: intake.linkage.worker_identity_fingerprint,
        worker_intake_reference_id: intake.linkage.worker_intake_reference_id,
        worker_intake_reference_fingerprint: intake.linkage.worker_intake_reference_fingerprint,
        worker_intake_admission_id: intake.admission_id,
        worker_intake_admission_fingerprint: intake.record_fingerprint,
        worker_intake_admission_status_fingerprint: fp("2"),
        live_enqueue_admission_decision_fingerprint: decisionFingerprint,
        inherited_limits_fingerprint: intake.inherited_limits.limits_fingerprint,
        linkage_fingerprint: fp("3"),
    },
    admission_decision: {
        schema: "live-enqueue-admission-decision-v1",
        decision_id: "ad433776-e578-5b65-af97-45b4ff3096cb",
        owner_operator_id: intake.operator_id,
        candidate_record_id: intake.candidate_record_id,
        worker_intake_admission_id: intake.admission_id,
        worker_intake_admission_fingerprint: intake.record_fingerprint,
        worker_queue_reservation_id: intake.linkage.queue_reservation_id,
        worker_queue_reservation_fingerprint: intake.linkage.queue_reservation_fingerprint,
        queue_item_reference_id: intake.linkage.queue_item_reference_id,
        queue_item_reference_fingerprint: intake.linkage.queue_item_reference_fingerprint,
        worker_identity_id: intake.linkage.worker_identity_id,
        worker_identity_fingerprint: intake.linkage.worker_identity_fingerprint,
        worker_intake_reference_id: intake.linkage.worker_intake_reference_id,
        worker_intake_reference_fingerprint: intake.linkage.worker_intake_reference_fingerprint,
        scope: "installation_live_enqueue_admission_only",
        decision: "preserve_non_enqueueing_live_enqueue_admission_evidence_only",
        evaluated_at: "2099-08-27T12:00:42Z",
        eligibility: "live_enqueue_admission_recorded",
        blockers: [...blockers],
        inherited_limits_fingerprint: intake.inherited_limits.limits_fingerprint,
        decision_fingerprint: decisionFingerprint,
        queue_item_constructed: false,
        request_serialized: false,
        request_sent: false,
        queue_enqueued: false,
        queue_dequeued: false,
        worker_contacted: false,
        worker_started: false,
        execution_authorized: false,
        ...authority,
    },
    inherited_limits: intake.inherited_limits,
    idempotency_key_fingerprint: fp("4"),
    request_fingerprint: fp("5"),
    subject_fingerprint: fp("6"),
    record_fingerprint: recordFingerprint,
    ...authority,
};

export const expiredLiveEnqueueAdmissionFixture: LiveEnqueueAdmissionV1 = {
    ...liveEnqueueAdmissionFixture,
    admission_id: "39c357ff-c3b5-556a-815b-a4c5761d4355",
    recorded_at: "2026-08-27T12:00:42Z",
    valid_until: "2026-08-27T12:01:12Z",
};

export const liveEnqueueAdmissionCollectionFixture: LiveEnqueueAdmissionCollectionV1 = {
    schema: "live-enqueue-admission-collection-v1",
    operator_id: intake.operator_id,
    candidate_record_id: intake.candidate_record_id,
    items: [liveEnqueueAdmissionFixture],
    count: 1,
    collection_fingerprint: fp("7"),
    ...authority,
};

export const blockedLiveEnqueueAdmissionResultFixture: LiveEnqueueAdmissionResultV1 = {
    schema: "live-enqueue-admission-result-v1",
    ok: false,
    admission: null,
    status: null,
    error: {
        schema: "live-enqueue-admission-error-v1",
        error_code: "evidence_expired",
        message: "live enqueue admission request could not be completed",
        retryable: false,
        correlation_fingerprint: fp("8"),
        redacted: true,
        ...authority,
    },
    correlation_fingerprint: fp("8"),
    ...authority,
};
