import { oneShotControlledDequeueFixture, oneShotControlledDequeueResultFixture } from "./oneShotControlledDequeue";
import { workerIntakeAdmissionFixture } from "./workerIntakeAdmission";
import { fp } from "./installationReadinessReview";
import type { OneShotDequeueWorkerBindingCollectionV1, OneShotDequeueWorkerBindingResultV1, OneShotDequeueWorkerBindingV1 } from "../types/oneShotDequeueWorkerBinding";

export const oneShotDequeueWorkerBindingAuthority = {
    evidence_only: true as const,
    reference_only: true as const,
    caller_supplied_credentials_allowed: false as const,
    caller_supplied_endpoint_allowed: false as const,
    caller_supplied_command_allowed: false as const,
    credential_material_present: false as const,
    endpoint_material_present: false as const,
    command_material_present: false as const,
    payload_schema_defined: false as const,
    payload_constructed: false as const,
    payload_serialized: false as const,
    payload_bytes: 0 as const,
    queue_polling_allowed: false as const,
    queue_claim_allowed: false as const,
    queue_lease_allowed: false as const,
    queue_ack_allowed: false as const,
    queue_mutation_allowed: false as const,
    worker_contact_allowed: false as const,
    worker_start_allowed: false as const,
    agent_invocation_allowed: false as const,
    execution_start_allowed: false as const,
    process_execution_allowed: false as const,
    store_contact_allowed: false as const,
    runtime_contact_allowed: false as const,
    dispatch_allowed: false as const,
    retry_allowed: false as const,
    scheduler_allowed: false as const,
    workflow_start_allowed: false as const,
    shell_execution_allowed: false as const,
    provider_mutation_allowed: false as const,
    repository_mutation_allowed: false as const,
    in_guest_mutation_allowed: false as const,
    installation_allowed: false as const,
    deployment_allowed: false as const,
    rollback_allowed: false as const,
    replay_bypass_allowed: false as const,
};

const blockers = ["store_contact_not_defined", "runtime_contact_not_defined", "worker_start_not_defined", "execution_start_boundary_not_defined"] as const;
const bindingId = "c83d7de2-6e64-59fd-9960-cf12ef4f964a";

export const oneShotDequeueWorkerBindingFixture: OneShotDequeueWorkerBindingV1 = {
    ...oneShotDequeueWorkerBindingAuthority,
    schema: "one-shot-dequeue-worker-binding-v1",
    binding_id: bindingId,
    operator_id: oneShotControlledDequeueFixture.operator_id,
    candidate_record_id: oneShotControlledDequeueFixture.candidate_record_id,
    recorded_at: "2099-08-27T12:00:42Z",
    valid_until: "2099-08-27T12:00:44Z",
    lifecycle: "active",
    binding_state: "readiness_gated",
    eligibility: "one_shot_dequeue_worker_binding_recorded",
    blockers: [...blockers],
    one_shot_controlled_dequeue: oneShotControlledDequeueFixture,
    one_shot_controlled_dequeue_status: oneShotControlledDequeueResultFixture.status!,
    worker_intake_admission: workerIntakeAdmissionFixture,
    worker_intake_admission_status: {
        ...workerIntakeAdmissionFixture,
        schema: "worker-intake-admission-status-v1",
        evaluated_at: "2099-08-27T12:00:42Z",
        status_fingerprint: fp,
    },
    worker_subject_fingerprint: workerIntakeAdmissionFixture.subject_fingerprint,
    queue_item_reference_fingerprint: workerIntakeAdmissionFixture.linkage.queue_item_reference_fingerprint,
    inherited_limits_fingerprint: workerIntakeAdmissionFixture.inherited_limits.limits_fingerprint,
    subject_fingerprint: fp,
    idempotency_key_fingerprint: fp,
    binding_record_fingerprint: fp,
    one_shot_dequeue_worker_binding_recorded: true,
};

export const oneShotDequeueWorkerBindingCollectionFixture: OneShotDequeueWorkerBindingCollectionV1 = {
    ...oneShotDequeueWorkerBindingAuthority,
    schema: "one-shot-dequeue-worker-binding-collection-v1",
    operator_id: oneShotDequeueWorkerBindingFixture.operator_id,
    candidate_record_id: oneShotDequeueWorkerBindingFixture.candidate_record_id,
    items: [oneShotDequeueWorkerBindingFixture],
    count: 1,
    collection_fingerprint: fp,
    one_shot_dequeue_worker_binding_recorded: false,
};

export const oneShotDequeueWorkerBindingResultFixture: OneShotDequeueWorkerBindingResultV1 = {
    ...oneShotDequeueWorkerBindingAuthority,
    schema: "one-shot-dequeue-worker-binding-result-v1",
    ok: true,
    outcome: "success",
    record: oneShotDequeueWorkerBindingFixture,
    status: {
        ...oneShotDequeueWorkerBindingAuthority,
        schema: "one-shot-dequeue-worker-binding-status-v1",
        binding_id: bindingId,
        operator_id: oneShotDequeueWorkerBindingFixture.operator_id,
        candidate_record_id: oneShotDequeueWorkerBindingFixture.candidate_record_id,
        lifecycle: "active",
        binding_state: "one_shot_dequeue_worker_binding_recorded",
        eligibility: "one_shot_dequeue_worker_binding_recorded",
        blockers: [...blockers],
        evaluated_at: "2099-08-27T12:00:43Z",
        valid_until: "2099-08-27T12:00:44Z",
        binding_record_fingerprint: fp,
        status_fingerprint: fp,
        one_shot_dequeue_worker_binding_recorded: true,
    },
    error: null,
    correlation_fingerprint: fp,
    one_shot_dequeue_worker_binding_recorded: true,
};
