import type { FingerprintV1 } from "../types/installationReadinessReview";
import type { OneShotLiveEnqueueCollectionV1, OneShotLiveEnqueueResultV1, OneShotLiveEnqueueStatusV1, OneShotLiveEnqueueV1 } from "../types/oneShotLiveEnqueue";
import { liveEnqueueAdmissionFixture } from "./liveEnqueueAdmission";

const fp = (value: string): FingerprintV1 => ({ algorithm: "sha256", canonicalization: "atlas-jcs-nfc-v1", value: value.repeat(64) });
const live = liveEnqueueAdmissionFixture;
const link = live.linkage;
const authority = {
    reference_only: true as const,
    payload_schema_defined: false as const,
    payload_constructed: false as const,
    payload_serialized: false as const,
    payload_bytes: 0 as const,
    dequeue_defined: false as const,
    dequeue_allowed: false as const,
    queue_polling_allowed: false as const,
    queue_claim_allowed: false as const,
    queue_lease_allowed: false as const,
    queue_ack_allowed: false as const,
    worker_contact_allowed: false as const,
    worker_authentication_allowed: false as const,
    worker_binding_allowed: false as const,
    worker_start_allowed: false as const,
    execution_start_allowed: false as const,
    runner_binding_allowed: false as const,
    dispatch_allowed: false as const,
    retry_allowed: false as const,
    resend_allowed: false as const,
    agent_invocation_allowed: false as const,
    workflow_start_allowed: false as const,
    scheduler_allowed: false as const,
    docker_execution_allowed: false as const,
    podman_execution_allowed: false as const,
    container_execution_allowed: false as const,
    shell_execution_allowed: false as const,
    process_execution_allowed: false as const,
    provider_mutation_allowed: false as const,
    repository_mutation_allowed: false as const,
    in_guest_mutation_allowed: false as const,
    installation_allowed: false as const,
    deployment_allowed: false as const,
    rollback_allowed: false as const,
    replay_bypass_allowed: false as const,
};
const blockers = ["dequeue_not_defined", "queue_polling_not_defined", "worker_start_not_defined", "execution_start_boundary_not_defined"] as const;
const enqueueId = "4b3beb58-c4b9-5b2b-9995-4f629abefaf4";
const itemFingerprint = fp("a");
const lineageFingerprint = fp("b");
const recordFingerprint = fp("c");

export const oneShotLiveEnqueueFixture: OneShotLiveEnqueueV1 = {
    schema: "one-shot-live-enqueue-v1",
    enqueue_id: enqueueId,
    operator_id: live.operator_id,
    candidate_record_id: live.candidate_record_id,
    recorded_at: "2099-08-27T12:00:44Z",
    valid_until: "2099-08-27T12:01:12Z",
    record_state: "recorded",
    lifecycle: "active",
    outcome: "one_shot_live_enqueue_recorded",
    blockers: [...blockers],
    lineage: {
        schema: "one-shot-live-enqueue-lineage-v1",
        operator_id: live.operator_id,
        candidate_record_id: live.candidate_record_id,
        live_enqueue_admission_linkage: link,
        v020_v040_chain_fingerprint: fp("d"),
        v020_v041_chain_fingerprint: fp("e"),
        live_enqueue_admission_id: live.admission_id,
        live_enqueue_admission_fingerprint: live.record_fingerprint,
        live_enqueue_admission_status_fingerprint: fp("f"),
        live_enqueue_admission_subject_fingerprint: live.subject_fingerprint,
        live_enqueue_admission_decision_fingerprint: link.live_enqueue_admission_decision_fingerprint,
        queue_reservation_id: link.queue_reservation_id,
        queue_reservation_fingerprint: link.queue_reservation_fingerprint,
        queue_reservation_status_fingerprint: link.queue_reservation_status_fingerprint,
        queue_intake_reference_id: link.queue_intake_reference_id,
        queue_intake_reference_fingerprint: link.queue_intake_reference_fingerprint,
        queue_item_reference_id: link.queue_item_reference_id,
        queue_item_reference_fingerprint: link.queue_item_reference_fingerprint,
        worker_intake_admission_id: link.worker_intake_admission_id,
        worker_intake_admission_fingerprint: link.worker_intake_admission_fingerprint,
        worker_intake_admission_status_fingerprint: link.worker_intake_admission_status_fingerprint,
        worker_identity_id: link.worker_identity_id,
        worker_identity_fingerprint: link.worker_identity_fingerprint,
        worker_intake_reference_id: link.worker_intake_reference_id,
        worker_intake_reference_fingerprint: link.worker_intake_reference_fingerprint,
        one_shot_queue_item_id: enqueueId,
        one_shot_queue_item_fingerprint: itemFingerprint,
        inherited_limits_fingerprint: link.inherited_limits_fingerprint,
        lineage_fingerprint: lineageFingerprint,
    },
    queue_item: {
        schema: "one-shot-live-enqueue-item-v1",
        queue_item_id: enqueueId,
        owner_operator_id: live.operator_id,
        candidate_record_id: live.candidate_record_id,
        live_enqueue_admission_id: live.admission_id,
        live_enqueue_admission_fingerprint: live.record_fingerprint,
        live_enqueue_admission_status_fingerprint: fp("f"),
        worker_queue_reservation_id: link.queue_reservation_id,
        worker_queue_reservation_fingerprint: link.queue_reservation_fingerprint,
        worker_intake_admission_id: link.worker_intake_admission_id,
        worker_intake_admission_fingerprint: link.worker_intake_admission_fingerprint,
        worker_identity_id: link.worker_identity_id,
        worker_identity_fingerprint: link.worker_identity_fingerprint,
        worker_intake_reference_id: link.worker_intake_reference_id,
        worker_intake_reference_fingerprint: link.worker_intake_reference_fingerprint,
        queue_intake_reference_id: link.queue_intake_reference_id,
        queue_intake_reference_fingerprint: link.queue_intake_reference_fingerprint,
        queue_item_reference_id: link.queue_item_reference_id,
        queue_item_reference_fingerprint: link.queue_item_reference_fingerprint,
        item_kind: "inert_reference_only_queue_item",
        trust_domain: "atlas-installation",
        scope: "installation_one_shot_live_enqueue_only",
        reference_only: true,
        item_state: "recorded",
        recorded_at: "2099-08-27T12:00:44Z",
        valid_until: "2099-08-27T12:01:12Z",
        lineage_fingerprint: lineageFingerprint,
        inherited_limits_fingerprint: link.inherited_limits_fingerprint,
        item_fingerprint: itemFingerprint,
        payload_schema_defined: false,
        payload_constructed: false,
        payload_serialized: false,
        payload_bytes: 0,
        dequeue_defined: false,
        dequeued: false,
        queue_polled: false,
        queue_claimed: false,
        queue_leased: false,
        worker_contacted: false,
        worker_started: false,
        execution_allowed: false,
    },
    inherited_limits: live.inherited_limits,
    idempotency_key_fingerprint: fp("1"),
    request_fingerprint: fp("2"),
    item_subject_fingerprint: fp("3"),
    record_fingerprint: recordFingerprint,
    one_shot_live_enqueue_recorded: true,
    ...authority,
};

export const oneShotLiveEnqueueCollectionFixture: OneShotLiveEnqueueCollectionV1 = {
    schema: "one-shot-live-enqueue-collection-v1",
    operator_id: live.operator_id,
    candidate_record_id: live.candidate_record_id,
    items: [oneShotLiveEnqueueFixture],
    count: 1,
    collection_fingerprint: fp("4"),
    one_shot_live_enqueue_recorded: false,
    ...authority,
};

export const oneShotLiveEnqueueStatusFixture: OneShotLiveEnqueueStatusV1 = {
    schema: "one-shot-live-enqueue-status-v1",
    enqueue_id: enqueueId,
    operator_id: live.operator_id,
    candidate_record_id: live.candidate_record_id,
    lifecycle: "active",
    outcome: "one_shot_live_enqueue_recorded",
    blockers: [...blockers],
    evaluated_at: "2099-08-27T12:00:45Z",
    valid_until: "2099-08-27T12:01:12Z",
    record_fingerprint: recordFingerprint,
    status_fingerprint: fp("5"),
    one_shot_live_enqueue_recorded: true,
    ...authority,
};

export const oneShotLiveEnqueueResultFixture: OneShotLiveEnqueueResultV1 = {
    schema: "one-shot-live-enqueue-result-v1",
    ok: true,
    outcome: "success",
    record: oneShotLiveEnqueueFixture,
    status: oneShotLiveEnqueueStatusFixture,
    error: null,
    correlation_fingerprint: fp("6"),
    one_shot_live_enqueue_recorded: true,
    ...authority,
};

export const indeterminateOneShotLiveEnqueueResultFixture: OneShotLiveEnqueueResultV1 = {
    schema: "one-shot-live-enqueue-result-v1",
    ok: false,
    outcome: "indeterminate",
    record: null,
    status: null,
    error: {
        schema: "one-shot-live-enqueue-error-v1",
        error_code: "append_indeterminate",
        message: "one-shot live enqueue request could not be completed",
        retryable: false,
        correlation_fingerprint: fp("5"),
        redacted: true,
        one_shot_live_enqueue_recorded: false,
        ...authority,
    },
    correlation_fingerprint: fp("5"),
    one_shot_live_enqueue_recorded: false,
    ...authority,
};
