import type { WorkflowOperationalLifecycle } from "../types/atlasAgent";

export function operationalLifecycle(
    overrides: Partial<WorkflowOperationalLifecycle> = {},
): WorkflowOperationalLifecycle {
    return {
        applicable: true,
        availability: "complete",
        consistency_status: "consistent",
        controlled_reason: null,
        workflow_id: "workflow-operational-1",
        workflow_state: "completed",
        agent_execution_stage: "verified",
        candidate_id: "candidate-1",
        planning_session_id: "planning-1",
        effect_kind: "operational_action",
        execution_intent: "restart-service",
        provider_id: "proxmox",
        resource_id: "110",
        resource_type: "qemu",
        target_label: "proxmox/qemu/110",
        operator_intent_record_id: "operator-intent-record-1",
        candidate_source_subsystem: "operator-intent",
        candidate_fingerprint: "candidate-fingerprint-v1:safe",
        plan_fingerprint: "operational-plan-fingerprint-v1:safe",
        preparation_approval: {
            approval_id: "approval-shell-1",
            decision_status: "approved",
            presentation_state: "resolved",
            actionable: false,
            expires_at: null,
        },
        action_approval: {
            approval_id: "approval-action-1",
            decision_status: "approved",
            presentation_state: "resolved",
            actionable: false,
            expires_at: "2026-08-16T00:10:00Z",
        },
        action_request_id: "request-1",
        request_digest: "operational-action-request-digest-v1:safe",
        target_fingerprint: "operational-target-fingerprint-v1:safe",
        target_version: "1",
        disruption_scope: "brief service interruption",
        request_created_at: "2026-08-16T00:00:00Z",
        request_expires_at: "2026-08-16T00:10:00Z",
        core_record_state: "verified",
        transitions: [
            { sequence: 1, state: "claimed", occurred_at: "2026-08-16T00:01:00Z" },
            { sequence: 2, state: "dispatching", occurred_at: "2026-08-16T00:02:00Z" },
            { sequence: 3, state: "verified", occurred_at: "2026-08-16T00:03:00Z" },
        ],
        barrier_crossed: true,
        barrier_crossing_count: 1,
        provider_operation_captured: true,
        provider_operation_capture_count: 1,
        dispatch_status: "succeeded",
        provider_operation_reference: "UPID:sanitized",
        dispatch_started_at: "2026-08-16T00:02:00Z",
        dispatch_completed_at: "2026-08-16T00:02:10Z",
        verification_status: "succeeded",
        observed_target_fingerprint: "operational-target-fingerprint-v1:safe",
        observed_state: "running",
        observed_health: "running",
        verification_started_at: "2026-08-16T00:02:11Z",
        verification_completed_at: "2026-08-16T00:03:00Z",
        verification_deadline: "2026-08-16T00:10:00Z",
        terminal: true,
        ...overrides,
    };
}
