import { fp } from "./installationReadinessReview";
import { oneShotLiveEnqueueFixture, oneShotLiveEnqueueStatusFixture } from "./oneShotLiveEnqueue";
import type { QueueObservationReceiptAuthorityV1, QueueObservationReceiptCollectionV1, QueueObservationReceiptResultV1, QueueObservationReceiptV1 } from "../types/queueObservation";

const authority: QueueObservationReceiptAuthorityV1 = {
    observation_only: true,
    reference_only: true,
    payload_schema_defined: false,
    payload_constructed: false,
    payload_serialized: false,
    payload_bytes: 0,
    executable_payload_allowed: false,
    live_enqueue_allowed: false,
    dequeue_defined: false,
    dequeue_allowed: false,
    queue_polling_allowed: false,
    queue_claim_allowed: false,
    queue_lease_allowed: false,
    queue_ack_allowed: false,
    worker_contact_allowed: false,
    worker_start_allowed: false,
    execution_start_allowed: false,
    dispatch_allowed: false,
    retry_allowed: false,
    resend_allowed: false,
    agent_invocation_allowed: false,
    workflow_start_allowed: false,
    docker_execution_allowed: false,
    podman_execution_allowed: false,
    container_execution_allowed: false,
    shell_execution_allowed: false,
    process_execution_allowed: false,
    provider_mutation_allowed: false,
    repository_mutation_allowed: false,
    in_guest_mutation_allowed: false,
    installation_allowed: false,
    deployment_allowed: false,
    rollback_allowed: false,
    replay_bypass_allowed: false,
};

const blockers = ["dequeue_not_defined", "queue_polling_not_defined", "worker_start_not_defined", "execution_start_boundary_not_defined"] as const;
const receiptId = "4b3beb58-c4b9-5b2b-9995-4f629abefaf5";
const receiptEvidence = {
    schema: "enqueue-receipt-evidence-v1" as const,
    enqueue_id: oneShotLiveEnqueueFixture.enqueue_id,
    operator_id: oneShotLiveEnqueueFixture.operator_id,
    candidate_record_id: oneShotLiveEnqueueFixture.candidate_record_id,
    enqueue_record_fingerprint: oneShotLiveEnqueueFixture.record_fingerprint,
    enqueue_status_fingerprint: oneShotLiveEnqueueStatusFixture.status_fingerprint,
    inert_queue_item_id: oneShotLiveEnqueueFixture.enqueue_id,
    inert_queue_item_fingerprint: oneShotLiveEnqueueFixture.queue_item.item_fingerprint,
    queue_intake_reference_id: oneShotLiveEnqueueFixture.queue_item.queue_intake_reference_id,
    queue_intake_reference_fingerprint: oneShotLiveEnqueueFixture.queue_item.queue_intake_reference_fingerprint,
    queue_item_reference_id: oneShotLiveEnqueueFixture.queue_item.queue_item_reference_id,
    queue_item_reference_fingerprint: oneShotLiveEnqueueFixture.queue_item.queue_item_reference_fingerprint,
    receipt_state: "receipt_recorded_for_contract_eligible_enqueue" as const,
    receipt_disposition: "contract_eligible" as const,
    recorded_at: "2099-08-27T12:00:46Z",
    valid_until: "2099-08-27T12:01:12Z",
    receipt_fingerprint: fp,
    payload_present: false as const,
    executable: false as const,
    effect_attempted: false as const,
};

export const queueObservationReceiptFixture: QueueObservationReceiptV1 = {
    ...authority,
    schema: "queue-observation-receipt-v1",
    receipt_id: receiptId,
    operator_id: oneShotLiveEnqueueFixture.operator_id,
    candidate_record_id: oneShotLiveEnqueueFixture.candidate_record_id,
    recorded_at: "2099-08-27T12:00:46Z",
    valid_until: "2099-08-27T12:01:12Z",
    lifecycle: "active",
    disposition: "observation_recorded",
    blockers: [...blockers],
    v042_enqueue: oneShotLiveEnqueueFixture,
    v042_enqueue_status: oneShotLiveEnqueueStatusFixture,
    receipt_evidence: receiptEvidence,
    queue_observation: {
        ...authority,
        schema: "queue-observation-v1",
        observation_id: receiptId,
        operator_id: oneShotLiveEnqueueFixture.operator_id,
        candidate_record_id: oneShotLiveEnqueueFixture.candidate_record_id,
        enqueue_id: oneShotLiveEnqueueFixture.enqueue_id,
        queue_identity: "abstract_installation_queue",
        item_identity: "inert_reference_only_queue_item",
        observation_state: "observed_recorded_not_consumable",
        lifecycle: "active",
        disposition: "observation_recorded",
        blockers: [...blockers],
        receipt_evidence: receiptEvidence,
        observed_at: "2099-08-27T12:00:46Z",
        valid_until: "2099-08-27T12:01:12Z",
        observation_fingerprint: fp,
    },
    lineage_fingerprint: fp,
    subject_fingerprint: fp,
    receipt_record_fingerprint: fp,
};

export const queueObservationCollectionFixture: QueueObservationReceiptCollectionV1 = {
    ...authority,
    schema: "queue-observation-receipt-collection-v1",
    operator_id: oneShotLiveEnqueueFixture.operator_id,
    candidate_record_id: oneShotLiveEnqueueFixture.candidate_record_id,
    items: [queueObservationReceiptFixture],
    count: 1,
    collection_fingerprint: fp,
    queue_observation_recorded: false,
};

export const queueObservationResultFixture: QueueObservationReceiptResultV1 = {
    ...authority,
    schema: "queue-observation-receipt-result-v1",
    ok: true,
    outcome: "success",
    record: queueObservationReceiptFixture,
    status: {
        ...authority,
        schema: "queue-observation-receipt-status-v1",
        receipt_id: receiptId,
        operator_id: oneShotLiveEnqueueFixture.operator_id,
        candidate_record_id: oneShotLiveEnqueueFixture.candidate_record_id,
        lifecycle: "active",
        disposition: "observation_recorded",
        blockers: [...blockers],
        evaluated_at: "2099-08-27T12:00:47Z",
        valid_until: "2099-08-27T12:01:12Z",
        receipt_record_fingerprint: fp,
        status_fingerprint: fp,
        queue_observation_recorded: true,
    },
    error: null,
    correlation_fingerprint: fp,
    queue_observation_recorded: true,
};

export const ambiguousQueueObservationResultFixture: QueueObservationReceiptResultV1 = {
    ...authority,
    schema: "queue-observation-receipt-result-v1",
    ok: false,
    outcome: "failure",
    record: null,
    status: null,
    error: {
        ...authority,
        schema: "queue-observation-receipt-error-v1",
        error_code: "ambiguous_state",
        message: "queue observation receipt request could not be completed",
        retryable: false,
        correlation_fingerprint: fp,
        redacted: true,
        queue_observation_recorded: false,
    },
    correlation_fingerprint: fp,
    queue_observation_recorded: false,
};
