import type { FingerprintV1 } from "../types/installationReadinessReview";
import type { WorkerIntakeAdmissionCollectionV1, WorkerIntakeAdmissionV1 } from "../types/workerIntakeAdmission";
import { workerQueueReservationResultFixture } from "./workerQueueReservation";

const fp = (value: string): FingerprintV1 => ({ algorithm: "sha256", canonicalization: "atlas-jcs-nfc-v1", value: value.repeat(64) });
const reservation = workerQueueReservationResultFixture.reservation!;
const authority = { evidence_only: true as const, live_enqueue_allowed: false as const, dequeue_allowed: false as const, queue_polling_allowed: false as const, worker_contact_allowed: false as const, worker_start_allowed: false as const, execution_start_allowed: false as const, runner_binding_allowed: false as const, dispatch_allowed: false as const, retry_allowed: false as const, resend_allowed: false as const, agent_invocation_allowed: false as const, workflow_start_allowed: false as const, docker_execution_allowed: false as const, podman_execution_allowed: false as const, shell_execution_allowed: false as const, process_execution_allowed: false as const, provider_mutation_allowed: false as const, repository_mutation_allowed: false as const, in_guest_mutation_allowed: false as const, installation_allowed: false as const, deployment_allowed: false as const, rollback_allowed: false as const, replay_bypass_allowed: false as const };
const admissionId = "16ca5b80-5d35-451f-a8cc-6de74c31c59c";
const workerIdentityId = "f0b912db-51ac-45cc-8209-5980780efd90";
const workerIntakeId = "1d1c9c18-8d82-409c-8be4-c42ab7763db9";
const decisionId = "212ba92c-ce23-57b5-91dc-4050c6a72bc5";
const workerIdentityFingerprint = fp("2");
const intakeReferenceFingerprint = fp("3");
const decisionFingerprint = fp("4");
const recordFingerprint = fp("5");
const blockers = ["live_enqueue_not_defined", "dequeue_not_defined", "worker_start_not_defined", "execution_start_boundary_not_defined"];

export const workerIntakeAdmissionFixture: WorkerIntakeAdmissionV1 = {
    schema: "worker-intake-admission-v1", admission_id: admissionId, operator_id: reservation.operator_id, candidate_record_id: reservation.candidate_record_id,
    recorded_at: "2099-08-27T12:00:36Z", valid_until: "2099-08-27T12:00:45Z", record_state: "recorded", lifecycle: "active", eligibility: "worker_intake_admission_recorded", blockers,
    linkage: { schema: "worker-intake-admission-linkage-v1", operator_id: reservation.operator_id, candidate_record_id: reservation.candidate_record_id, worker_queue_reservation_linkage: reservation.linkage, v020_v038_chain_fingerprint: fp("6"), readiness_review_fingerprint: reservation.linkage.readiness_review_fingerprint, permission_grant_fingerprint: reservation.linkage.permission_grant_fingerprint, execution_admission_id: reservation.linkage.execution_admission_id, execution_admission_fingerprint: reservation.linkage.execution_admission_fingerprint, runner_binding_plan_id: reservation.linkage.runner_binding_plan_id, runner_binding_plan_fingerprint: reservation.linkage.runner_binding_plan_fingerprint, runner_binding_plan_status_fingerprint: reservation.linkage.runner_binding_plan_status_fingerprint, runner_reference_id: reservation.linkage.runner_reference_id, runner_reference_fingerprint: reservation.linkage.runner_reference_fingerprint, worker_admission_stub_id: reservation.linkage.worker_admission_stub_id, worker_admission_stub_fingerprint: reservation.linkage.worker_admission_stub_fingerprint, worker_admission_stub_status_fingerprint: reservation.linkage.worker_admission_stub_status_fingerprint, worker_reference_id: reservation.linkage.worker_reference_id, worker_reference_fingerprint: reservation.linkage.worker_reference_fingerprint, queue_reservation_id: reservation.reservation_id, queue_reservation_fingerprint: reservation.record_fingerprint, queue_reservation_status_fingerprint: workerQueueReservationResultFixture.status!.status_fingerprint, queue_intake_reference_id: reservation.linkage.queue_intake_reference_id, queue_intake_reference_fingerprint: reservation.linkage.queue_intake_reference_fingerprint, queue_item_reference_id: reservation.linkage.queue_item_reference_id, queue_item_reference_fingerprint: reservation.linkage.queue_item_reference_fingerprint, worker_identity_id: workerIdentityId, worker_identity_fingerprint: workerIdentityFingerprint, worker_intake_reference_id: workerIntakeId, worker_intake_reference_fingerprint: intakeReferenceFingerprint, worker_intake_admission_decision_fingerprint: decisionFingerprint, inherited_limits_fingerprint: reservation.inherited_limits.limits_fingerprint, linkage_fingerprint: fp("7") },
    worker_identity: { schema: "worker-intake-worker-identity-v1", worker_identity_id: workerIdentityId, owner_operator_id: reservation.operator_id, candidate_record_id: reservation.candidate_record_id, worker_queue_reservation_id: reservation.reservation_id, worker_queue_reservation_fingerprint: reservation.record_fingerprint, worker_reference_id: reservation.linkage.worker_reference_id, worker_reference_fingerprint: reservation.linkage.worker_reference_fingerprint, queue_intake_reference_id: reservation.linkage.queue_intake_reference_id, queue_intake_reference_fingerprint: reservation.linkage.queue_intake_reference_fingerprint, queue_item_reference_id: reservation.linkage.queue_item_reference_id, queue_item_reference_fingerprint: reservation.linkage.queue_item_reference_fingerprint, worker_kind: "isolated_installation_worker", trust_domain: "atlas-installation", scope: "installation_worker_intake_admission_only", eligibility: "eligible_for_intake_admission_evidence_only", identity_fingerprint: fp("8"), capability_profile_fingerprint: fp("9"), inherited_limits: reservation.inherited_limits, inherited_limits_fingerprint: reservation.inherited_limits.limits_fingerprint, valid_from: "2099-08-27T12:00:36Z", valid_until: "2099-08-27T12:00:45Z", registered: false, available: false, reachable: false, authenticated: false, contacted: false, reserved: false, started: false, execution_allowed: false, worker_identity_fingerprint: workerIdentityFingerprint },
    worker_intake_reference: { schema: "worker-intake-reference-v1", worker_intake_reference_id: workerIntakeId, owner_operator_id: reservation.operator_id, candidate_record_id: reservation.candidate_record_id, worker_queue_reservation_id: reservation.reservation_id, worker_queue_reservation_fingerprint: reservation.record_fingerprint, worker_identity_id: workerIdentityId, worker_identity_fingerprint: workerIdentityFingerprint, queue_intake_reference_id: reservation.linkage.queue_intake_reference_id, queue_intake_reference_fingerprint: reservation.linkage.queue_intake_reference_fingerprint, queue_item_reference_id: reservation.linkage.queue_item_reference_id, queue_item_reference_fingerprint: reservation.linkage.queue_item_reference_fingerprint, intake_kind: "abstract_worker_intake", trust_domain: "atlas-installation", scope: "installation_worker_intake_admission_only", eligibility: "eligible_for_intake_admission_evidence_only", valid_from: "2099-08-27T12:00:36Z", valid_until: "2099-08-27T12:00:45Z", intake_reference_fingerprint: intakeReferenceFingerprint, intake_protocol: "none", intake_exists: false, intake_open: false, endpoint_known: false, credential_known: false, payload_schema_defined: false, serialization_allowed: false, live_enqueue_allowed: false, worker_start_allowed: false },
    admission_decision: { schema: "worker-intake-admission-decision-v1", decision_id: decisionId, owner_operator_id: reservation.operator_id, candidate_record_id: reservation.candidate_record_id, worker_queue_reservation_id: reservation.reservation_id, worker_queue_reservation_fingerprint: reservation.record_fingerprint, worker_identity_id: workerIdentityId, worker_identity_fingerprint: workerIdentityFingerprint, worker_intake_reference_id: workerIntakeId, worker_intake_reference_fingerprint: intakeReferenceFingerprint, scope: "installation_worker_intake_admission_only", decision: "preserve_non_executing_worker_intake_admission_evidence_only", evaluated_at: "2099-08-27T12:00:36Z", eligibility: "worker_intake_admission_recorded", blockers, inherited_limits_fingerprint: reservation.inherited_limits.limits_fingerprint, decision_fingerprint: decisionFingerprint, payload_constructed: false, request_serialized: false, request_sent: false, queue_enqueued: false, queue_dequeued: false, worker_contacted: false, worker_started: false, execution_authorized: false },
    inherited_limits: reservation.inherited_limits, idempotency_key_fingerprint: fp("a"), request_fingerprint: fp("b"), subject_fingerprint: fp("c"), record_fingerprint: recordFingerprint, ...authority,
};

export const workerIntakeAdmissionCollectionFixture: WorkerIntakeAdmissionCollectionV1 = {
    schema: "worker-intake-admission-collection-v1", operator_id: reservation.operator_id, candidate_record_id: reservation.candidate_record_id,
    items: [workerIntakeAdmissionFixture], count: 1, collection_fingerprint: fp("d"), ...authority,
};
