import type { FingerprintV1 } from "../types/installationReadinessReview";
import type { WorkerAdmissionStubResultV1 } from "../types/workerAdmissionStub";
import { runnerBindingPlanResultFixture } from "./runnerBindingPlan";

const fp = (value: string): FingerprintV1 => ({ algorithm: "sha256", canonicalization: "atlas-jcs-nfc-v1", value: value.repeat(64) });
const plan = runnerBindingPlanResultFixture.plan!;
const workerId = "77126d0a-01d3-43f3-959a-5106547936bb";
const stubId = "1392e17e-6d79-4d92-b428-a676b39feee9";
const intentId = "5af90ae1-ba3d-567b-ac21-9d439df703a7";
const authority = { evidence_only: true as const, runner_binding_allowed: false as const, worker_registered: false as const, worker_contacted: false as const, worker_reserved: false as const, worker_bound: false as const, worker_started: false as const, queue_created: false as const, queue_allowed: false as const, work_enqueued: false as const, enqueue_allowed: false as const, dispatch_allowed: false as const, execution_start_allowed: false as const, execution_authorized: false as const, installation_allowed: false as const, retry_allowed: false as const, resend_allowed: false as const, agent_invocation_allowed: false as const, workflow_allowed: false as const, docker_allowed: false as const, podman_allowed: false as const, shell_allowed: false as const, process_allowed: false as const, provider_mutation_allowed: false as const, repository_mutation_allowed: false as const, in_guest_mutation_allowed: false as const, deployment_allowed: false as const, rollback_allowed: false as const, replay_allowed: false as const };
const resultAuthority = { evidence_only: true as const, worker_registration_allowed: false as const, worker_contact_allowed: false as const, worker_reservation_allowed: false as const, worker_binding_allowed: false as const, worker_start_allowed: false as const, queue_allowed: false as const, enqueue_allowed: false as const, dispatch_allowed: false as const, execution_start_allowed: false as const, execution_authorized: false as const, installation_allowed: false as const, agent_invocation_allowed: false as const, workflow_allowed: false as const, mutation_allowed: false as const, deployment_allowed: false as const, rollback_allowed: false as const, retry_allowed: false as const, replay_allowed: false as const };
const intent = { schema: "worker-admission-intent-v1" as const, intent_id: intentId, operator_id: plan.operator_id, candidate_record_id: plan.candidate_record_id, runner_binding_plan_id: plan.plan_id, runner_binding_plan_fingerprint: plan.plan_fingerprint, worker_reference_id: workerId, worker_reference_fingerprint: fp("1"), inherited_limits_fingerprint: plan.limits.limits_fingerprint, scope: "installation_worker_admission_stub_only" as const, intent: "preserve_non_executing_worker_admission_evidence_only" as const, requested_at: "2026-08-27T12:00:33Z", intent_fingerprint: fp("2"), queue_requested: false as const, dispatch_requested: false as const, worker_start_requested: false as const, execution_requested: false as const, agent_invocation_requested: false as const, mutation_requested: false as const };
const intake = { schema: "worker-admission-intake-stub-v1" as const, intent_id: intentId, intent_fingerprint: intent.intent_fingerprint, worker_reference_id: workerId, worker_reference_fingerprint: intent.worker_reference_fingerprint, scope: "installation_worker_admission_stub_only" as const, intake_state: "undefined" as const, intake_protocol: "none" as const, intake_fingerprint: fp("3"), queue_selected: false as const, queue_created: false as const, intake_open: false as const, payload_constructed: false as const, request_serialized: false as const, request_sent: false as const, worker_contacted: false as const, worker_started: false as const, execution_authorized: false as const };
const worker = { schema: "installation-worker-reference-v1" as const, worker_reference_id: workerId, owner_operator_id: plan.operator_id, worker_kind: "isolated_installation_worker" as const, trust_domain: "atlas-installation" as const, scope: "installation_worker_admission_stub_only" as const, eligibility: "eligible_for_admission_stub_only" as const, runner_reference_id: plan.runner_reference.runner_reference_id, runner_reference_fingerprint: plan.runner_reference.reference_fingerprint, identity_fingerprint: fp("4"), capability_profile_fingerprint: fp("5"), inherited_limits: plan.limits, inherited_limits_fingerprint: plan.limits.limits_fingerprint, valid_from: "2026-08-27T12:00:25Z", valid_until: "2026-08-27T12:00:45Z", reference_fingerprint: intent.worker_reference_fingerprint, registered: false as const, available: false as const, reachable: false as const, authenticated: false as const, contacted: false as const, reserved: false as const, bound: false as const, queue_known: false as const, intake_open: false as const, invocation_allowed: false as const };
const stubFingerprint = fp("6");

export const workerAdmissionStubResultFixture: WorkerAdmissionStubResultV1 = {
    schema: "worker-admission-stub-result-v1", disposition: "recorded",
    stub: {
        schema: "worker-admission-stub-v1", stub_id: stubId, operator_id: plan.operator_id,
        candidate_record_id: plan.candidate_record_id, recorded_at: "2026-08-27T12:00:33Z",
        valid_until: "2026-08-27T12:00:45Z", record_state: "recorded", lifecycle: "active",
        eligibility: "worker_admission_stubbed", blockers: ["worker_not_started", "queue_boundary_not_defined", "execution_start_boundary_not_defined"],
        linkage: { schema: "worker-admission-stub-linkage-v1", operator_id: plan.operator_id, candidate_record_id: plan.candidate_record_id, runner_binding_plan_linkage: plan.linkage, v020_v036_chain_fingerprint: fp("7"), readiness_review_fingerprint: plan.linkage.readiness_review_fingerprint, permission_grant_fingerprint: plan.linkage.permission_grant_fingerprint, execution_admission_id: plan.linkage.execution_admission_id, execution_admission_fingerprint: plan.linkage.execution_admission_fingerprint, runner_binding_plan_id: plan.plan_id, runner_binding_plan_fingerprint: plan.plan_fingerprint, runner_binding_plan_status_fingerprint: runnerBindingPlanResultFixture.status!.status_fingerprint, runner_reference_id: plan.runner_reference.runner_reference_id, runner_reference_fingerprint: plan.runner_reference.reference_fingerprint, worker_reference_id: workerId, worker_reference_fingerprint: worker.reference_fingerprint, worker_identity_fingerprint: worker.identity_fingerprint, worker_capability_profile_fingerprint: worker.capability_profile_fingerprint, worker_admission_intent_fingerprint: intent.intent_fingerprint, worker_admission_intake_fingerprint: intake.intake_fingerprint, inherited_limits_fingerprint: plan.limits.limits_fingerprint, linkage_fingerprint: fp("8") },
        worker_admission_intent: intent, worker_admission_intake: intake, worker_reference: worker,
        inherited_limits: plan.limits, idempotency_key_fingerprint: fp("9"), request_fingerprint: fp("a"), stub_fingerprint: stubFingerprint, ...authority,
    },
    status: { schema: "worker-admission-stub-status-v1", stub_id: stubId, observed_at: "2026-08-27T12:00:33Z", lifecycle: "active", eligibility: "worker_admission_stubbed", blockers: ["worker_not_started", "queue_boundary_not_defined", "execution_start_boundary_not_defined"], status_fingerprint: fp("b"), evidence_only: true, worker_started: false, work_enqueued: false, execution_authorized: false, replay_allowed: false },
    audit_evidence: { schema: "worker-admission-stub-audit-evidence-v1", event: "worker_admission_stub_recorded", outcome: "recorded", operator_fingerprint: fp("c"), candidate_record_fingerprint: fp("d"), stub_fingerprint: stubFingerprint, correlation_fingerprint: fp("e"), occurred_at: "2026-08-27T12:00:33Z", audit_fingerprint: fp("f"), evidence_only: true, worker_contact_attempted: false, worker_start_attempted: false, enqueue_attempted: false, dispatch_attempted: false, execution_start_attempted: false, agent_invocation_attempted: false, workflow_start_attempted: false, process_execution_attempted: false, mutation_attempted: false, replay_attempted: false, effect_attempted: false },
    error: null, ...resultAuthority,
};
