import type { FingerprintV1 } from "../types/installationReadinessReview";
import type { WorkerQueueReservationResultV1 } from "../types/workerQueueReservation";
import { workerAdmissionStubResultFixture } from "./workerAdmissionStub";

const fp = (value: string): FingerprintV1 => ({ algorithm: "sha256", canonicalization: "atlas-jcs-nfc-v1", value: value.repeat(64) });
const stub = workerAdmissionStubResultFixture.stub!;
const reservationId = "54ce84e1-1957-4ca7-a545-0eb7b818df5c";
const queueIntakeId = "5938877b-f0ff-426d-8d76-29c3ec43a845";
const queueItemId = "d583ab23-703a-5f11-bf63-e3d67e9c503e";
const recordFingerprint = fp("2");
const authority = { evidence_only: true as const, live_enqueue_allowed: false as const, dequeue_allowed: false as const, queue_polling_allowed: false as const, worker_contact_allowed: false as const, worker_start_allowed: false as const, execution_start_allowed: false as const, runner_binding_allowed: false as const, dispatch_allowed: false as const, retry_allowed: false as const, resend_allowed: false as const, agent_invocation_allowed: false as const, workflow_start_allowed: false as const, docker_execution_allowed: false as const, podman_execution_allowed: false as const, shell_execution_allowed: false as const, process_execution_allowed: false as const, provider_mutation_allowed: false as const, repository_mutation_allowed: false as const, in_guest_mutation_allowed: false as const, installation_allowed: false as const, deployment_allowed: false as const, rollback_allowed: false as const, replay_bypass_allowed: false as const };

export const workerQueueReservationResultFixture: WorkerQueueReservationResultV1 = {
    schema: "worker-queue-reservation-result-v1", disposition: "recorded",
    reservation: {
        schema: "worker-queue-reservation-v1", reservation_id: reservationId, operator_id: stub.operator_id, candidate_record_id: stub.candidate_record_id,
        recorded_at: "2026-08-27T12:00:34Z", valid_until: "2026-08-27T12:00:45Z", record_state: "recorded", lifecycle: "active", eligibility: "worker_queue_reservation_recorded",
        blockers: ["live_enqueue_not_defined", "dequeue_not_defined", "worker_start_not_defined", "execution_start_boundary_not_defined"],
        linkage: { schema: "worker-queue-reservation-linkage-v1", operator_id: stub.operator_id, candidate_record_id: stub.candidate_record_id, worker_admission_stub_linkage: stub.linkage, v020_v037_chain_fingerprint: fp("3"), readiness_review_fingerprint: stub.linkage.readiness_review_fingerprint, permission_grant_fingerprint: stub.linkage.permission_grant_fingerprint, execution_admission_id: stub.linkage.execution_admission_id, execution_admission_fingerprint: stub.linkage.execution_admission_fingerprint, runner_binding_plan_id: stub.linkage.runner_binding_plan_id, runner_binding_plan_fingerprint: stub.linkage.runner_binding_plan_fingerprint, runner_binding_plan_status_fingerprint: stub.linkage.runner_binding_plan_status_fingerprint, runner_reference_id: stub.linkage.runner_reference_id, runner_reference_fingerprint: stub.linkage.runner_reference_fingerprint, worker_admission_stub_id: stub.stub_id, worker_admission_stub_fingerprint: stub.stub_fingerprint, worker_admission_stub_status_fingerprint: workerAdmissionStubResultFixture.status!.status_fingerprint, worker_reference_id: stub.worker_reference.worker_reference_id, worker_reference_fingerprint: stub.worker_reference.reference_fingerprint, worker_admission_intent_fingerprint: stub.worker_admission_intent.intent_fingerprint, worker_intake_stub_fingerprint: stub.worker_admission_intake.intake_fingerprint, queue_intake_reference_id: queueIntakeId, queue_intake_reference_fingerprint: fp("4"), queue_item_reference_id: queueItemId, queue_item_reference_fingerprint: fp("5"), inherited_limits_fingerprint: stub.inherited_limits.limits_fingerprint, linkage_fingerprint: fp("6") },
        queue_intake_reference: { schema: "worker-queue-intake-reference-v1", queue_intake_reference_id: queueIntakeId, owner_operator_id: stub.operator_id, candidate_record_id: stub.candidate_record_id, worker_admission_stub_id: stub.stub_id, worker_admission_stub_fingerprint: stub.stub_fingerprint, worker_reference_id: stub.worker_reference.worker_reference_id, worker_reference_fingerprint: stub.worker_reference.reference_fingerprint, queue_kind: "abstract_installation_queue", trust_domain: "atlas-installation", scope: "installation_worker_queue_reservation_only", eligibility: "eligible_for_reservation_evidence_only", identity_fingerprint: fp("7"), capability_fingerprint: fp("8"), inherited_limits: stub.inherited_limits, inherited_limits_fingerprint: stub.inherited_limits.limits_fingerprint, valid_from: "2026-08-27T12:00:34Z", valid_until: "2026-08-27T12:00:45Z", reference_fingerprint: fp("4"), queue_exists: false, queue_reachable: false, queue_authenticated: false, queue_contacted: false, reservation_endpoint_known: false, live_enqueue_allowed: false, dequeue_allowed: false },
        queue_item_reference: { schema: "worker-queue-item-reference-v1", queue_item_reference_id: queueItemId, owner_operator_id: stub.operator_id, candidate_record_id: stub.candidate_record_id, worker_admission_stub_id: stub.stub_id, worker_admission_stub_fingerprint: stub.stub_fingerprint, queue_intake_reference_id: queueIntakeId, queue_intake_reference_fingerprint: fp("4"), worker_reference_id: stub.worker_reference.worker_reference_id, worker_reference_fingerprint: stub.worker_reference.reference_fingerprint, item_kind: "installation_evidence_reference_only", scope: "installation_worker_queue_reservation_only", inherited_limits_fingerprint: stub.inherited_limits.limits_fingerprint, created_at: "2026-08-27T12:00:34Z", item_fingerprint: fp("5"), payload_defined: false, serialized: false, enqueued: false, dequeued: false, claimed: false, executable: false },
        inherited_limits: stub.inherited_limits, idempotency_key_fingerprint: fp("9"), request_fingerprint: fp("a"), subject_fingerprint: fp("b"), record_fingerprint: recordFingerprint, ...authority,
    },
    status: { schema: "worker-queue-reservation-status-v1", reservation_id: reservationId, operator_id: stub.operator_id, candidate_record_id: stub.candidate_record_id, observed_at: "2026-08-27T12:00:35Z", valid_until: "2026-08-27T12:00:45Z", lifecycle: "active", eligibility: "worker_queue_reservation_recorded", blockers: ["live_enqueue_not_defined", "dequeue_not_defined", "worker_start_not_defined", "execution_start_boundary_not_defined"], record_fingerprint: recordFingerprint, status_fingerprint: fp("c"), ...authority },
    audit_evidence: { schema: "worker-queue-reservation-audit-v1", event: "reservation_recorded", outcome: "recorded", operator_fingerprint: fp("d"), candidate_record_fingerprint: fp("e"), reservation_id: reservationId, subject_fingerprint: fp("b"), record_fingerprint: recordFingerprint, correlation_fingerprint: fp("f"), occurred_at: "2026-08-27T12:00:35Z", audit_fingerprint: fp("1"), ...authority },
    error: null, ...authority,
};
